// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

import com.mendix.core.Core;

public enum Enum_DistanceUnit
{
	KILOMETER("ca681115-1569-4bc3-8355-28b5cb25972c"),
	STATUTE_MILE("ae3ade93-332a-4d9e-83d2-99407f3807a3"),
	NAUTICAL_MILE("b34eb91d-6d46-4e13-8952-806f0b79c44c");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_DistanceUnit(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
