// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

import com.mendix.core.Core;

public enum GeocodingProvider
{
	Google("d887b437-5c77-4706-a912-48091e8557c7"),
	Geocodio("9af8d9c7-9bd9-44b6-b48d-a85657055613"),
	LocationIQ("483c6ae5-b625-4d66-91be-ba656262bd02"),
	MapQuest("442433e9-f296-45bb-8afb-83dacb0b7b17");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
