// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

import com.mendix.core.Core;

public enum Platform
{
	Web("d0869110-b03d-4f60-b5ab-0ca949798310"),
	Native_mobile("7abf7a89-9968-47da-8ef5-3ff03cadeade"),
	Hybrid_mobile("797d6710-01c2-46b8-b029-da1d3e129a2c");

	private final java.lang.String i18nCaptionKey;
	
	private Platform(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
