// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

import com.mendix.core.Core;

public enum Filter_Operators
{
	contains("d6a956e7-4cf2-4c13-af65-970e113a5f6e"),
	startsWith("20a25f8d-5f99-4da6-a3a6-0717fbfe0ac4"),
	endsWith("92f9e86f-cd26-4198-92d7-3a5730b6dcaa"),
	between("3be8e45e-c386-4f2d-b636-4b0614c6d851"),
	greater("3595d42b-c96e-40d4-92ae-4f9254cda48d"),
	greaterEqual("d9d726a7-18c9-45db-a152-a2959052dc08"),
	equal("840f3eff-4d05-44dd-b741-c7eb3c5dee64"),
	notEqual("b914d009-c304-48f4-9e6a-b69927dee359"),
	smaller("e5344d46-fad7-4e58-864d-02319d66c93e"),
	smallerEqual("18490fc6-7948-4df5-9786-8479dc11f6be"),
	empty("aaefa6f4-9448-4133-8dea-066864665a57"),
	notEmpty("f103d12f-5fe0-4134-93b2-9f5aceb81bb4");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
