// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies;

import com.mendix.core.Core;

public enum PictureQuality
{
	original("cd1c91a9-96b2-4da0-b4c3-7911daffe14c"),
	low("fbeec490-6249-480e-8027-9db7c4bccdbe"),
	medium("40d8e34b-bfc2-4d3f-a5ed-922c2ce1d15b"),
	high("c87a6069-8293-4903-92e3-1873138dbecf"),
	custom("f1d554b2-fb0e-415f-852c-53bcf74c2c99");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
