// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feedbackmodule.proxies;

import com.mendix.core.Core;

public enum LogNodes
{
	FeedbackModule("eda75b80-b7bb-4c62-85d8-565c13dbb089");

	private final java.lang.String i18nCaptionKey;
	
	private LogNodes(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
