// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feedbackmodule.proxies;

import com.mendix.core.Core;

public enum TranslationLanguages
{
	Dutch("64e9056e-f6e5-454e-8d60-c166ba0467be"),
	English("8dda896f-825b-4d28-bfcc-aa693f7c14bd"),
	French("3e401125-dc9a-4222-ba2d-ca03943ca19b"),
	German("579b4d17-4b16-4726-81a1-46456df57471"),
	Hindi("7e1daed3-b270-45c1-ba28-4acf2b9e8efd"),
	Portuguese("1528a6e3-dbb1-47af-8a39-4d1a6c320c9f"),
	Spanish("204c8f64-88b3-4c7d-a241-11f8a935317d"),
	Turkish("30aa62c0-e8f1-44e2-80e0-a928324daf84");

	private final java.lang.String i18nCaptionKey;
	
	private TranslationLanguages(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
