// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class JedinicaMere implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject jedinicaMereMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.JedinicaMere";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		nazivJedinice("nazivJedinice"),
		skraceniNaziv("skraceniNaziv"),
		JedinicaMere_RobaIliUsluga("MyFirstModule.JedinicaMere_RobaIliUsluga");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public JedinicaMere(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected JedinicaMere(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject jedinicaMereMendixObject)
	{
		if (jedinicaMereMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!jedinicaMereMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.jedinicaMereMendixObject = jedinicaMereMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.JedinicaMere initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.JedinicaMere(context, mendixObject);
	}

	public static myfirstmodule.proxies.JedinicaMere load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.JedinicaMere.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.JedinicaMere> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.JedinicaMere.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of nazivJedinice
	 */
	public final java.lang.String getnazivJedinice()
	{
		return getnazivJedinice(getContext());
	}

	/**
	 * @param context
	 * @return value of nazivJedinice
	 */
	public final java.lang.String getnazivJedinice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.nazivJedinice.toString());
	}

	/**
	 * Set value of nazivJedinice
	 * @param nazivjedinice
	 */
	public final void setnazivJedinice(java.lang.String nazivjedinice)
	{
		setnazivJedinice(getContext(), nazivjedinice);
	}

	/**
	 * Set value of nazivJedinice
	 * @param context
	 * @param nazivjedinice
	 */
	public final void setnazivJedinice(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nazivjedinice)
	{
		getMendixObject().setValue(context, MemberNames.nazivJedinice.toString(), nazivjedinice);
	}

	/**
	 * @return value of skraceniNaziv
	 */
	public final java.lang.String getskraceniNaziv()
	{
		return getskraceniNaziv(getContext());
	}

	/**
	 * @param context
	 * @return value of skraceniNaziv
	 */
	public final java.lang.String getskraceniNaziv(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.skraceniNaziv.toString());
	}

	/**
	 * Set value of skraceniNaziv
	 * @param skraceninaziv
	 */
	public final void setskraceniNaziv(java.lang.String skraceninaziv)
	{
		setskraceniNaziv(getContext(), skraceninaziv);
	}

	/**
	 * Set value of skraceniNaziv
	 * @param context
	 * @param skraceninaziv
	 */
	public final void setskraceniNaziv(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String skraceninaziv)
	{
		getMendixObject().setValue(context, MemberNames.skraceniNaziv.toString(), skraceninaziv);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of JedinicaMere_RobaIliUsluga
	 */
	public final myfirstmodule.proxies.RobaIliUsluga getJedinicaMere_RobaIliUsluga() throws com.mendix.core.CoreException
	{
		return getJedinicaMere_RobaIliUsluga(getContext());
	}

	/**
	 * @param context
	 * @return value of JedinicaMere_RobaIliUsluga
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.RobaIliUsluga getJedinicaMere_RobaIliUsluga(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.RobaIliUsluga result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JedinicaMere_RobaIliUsluga.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.RobaIliUsluga.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of JedinicaMere_RobaIliUsluga
	 * @param jedinicamere_robailiusluga
	 */
	public final void setJedinicaMere_RobaIliUsluga(myfirstmodule.proxies.RobaIliUsluga jedinicamere_robailiusluga)
	{
		setJedinicaMere_RobaIliUsluga(getContext(), jedinicamere_robailiusluga);
	}

	/**
	 * Set value of JedinicaMere_RobaIliUsluga
	 * @param context
	 * @param jedinicamere_robailiusluga
	 */
	public final void setJedinicaMere_RobaIliUsluga(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.RobaIliUsluga jedinicamere_robailiusluga)
	{
		if (jedinicamere_robailiusluga == null) {
			getMendixObject().setValue(context, MemberNames.JedinicaMere_RobaIliUsluga.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.JedinicaMere_RobaIliUsluga.toString(), jedinicamere_robailiusluga.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return jedinicaMereMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.JedinicaMere that = (myfirstmodule.proxies.JedinicaMere) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
