// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Kategorija implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject kategorijaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Kategorija";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		nazivKategorije("nazivKategorije"),
		Kategorija_Preduzece("MyFirstModule.Kategorija_Preduzece");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Kategorija(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Kategorija(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject kategorijaMendixObject)
	{
		if (kategorijaMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!kategorijaMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.kategorijaMendixObject = kategorijaMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Kategorija initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Kategorija(context, mendixObject);
	}

	public static myfirstmodule.proxies.Kategorija load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Kategorija.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Kategorija> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Kategorija.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of nazivKategorije
	 */
	public final java.lang.String getnazivKategorije()
	{
		return getnazivKategorije(getContext());
	}

	/**
	 * @param context
	 * @return value of nazivKategorije
	 */
	public final java.lang.String getnazivKategorije(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.nazivKategorije.toString());
	}

	/**
	 * Set value of nazivKategorije
	 * @param nazivkategorije
	 */
	public final void setnazivKategorije(java.lang.String nazivkategorije)
	{
		setnazivKategorije(getContext(), nazivkategorije);
	}

	/**
	 * Set value of nazivKategorije
	 * @param context
	 * @param nazivkategorije
	 */
	public final void setnazivKategorije(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nazivkategorije)
	{
		getMendixObject().setValue(context, MemberNames.nazivKategorije.toString(), nazivkategorije);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Kategorija_Preduzece
	 */
	public final myfirstmodule.proxies.Preduzece getKategorija_Preduzece() throws com.mendix.core.CoreException
	{
		return getKategorija_Preduzece(getContext());
	}

	/**
	 * @param context
	 * @return value of Kategorija_Preduzece
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Preduzece getKategorija_Preduzece(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Preduzece result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Kategorija_Preduzece.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Preduzece.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Kategorija_Preduzece
	 * @param kategorija_preduzece
	 */
	public final void setKategorija_Preduzece(myfirstmodule.proxies.Preduzece kategorija_preduzece)
	{
		setKategorija_Preduzece(getContext(), kategorija_preduzece);
	}

	/**
	 * Set value of Kategorija_Preduzece
	 * @param context
	 * @param kategorija_preduzece
	 */
	public final void setKategorija_Preduzece(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Preduzece kategorija_preduzece)
	{
		if (kategorija_preduzece == null) {
			getMendixObject().setValue(context, MemberNames.Kategorija_Preduzece.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Kategorija_Preduzece.toString(), kategorija_preduzece.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return kategorijaMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Kategorija that = (myfirstmodule.proxies.Kategorija) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
