// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class PopisniDokument implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject popisniDokumentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.PopisniDokument";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		brojPopisa("brojPopisa"),
		datumDokumenta("datumDokumenta"),
		datumKnjizenja("datumKnjizenja"),
		datumPopisa("datumPopisa"),
		statusPopisa("statusPopisa"),
		PopisniDokument_Magacin("MyFirstModule.PopisniDokument_Magacin"),
		predsednik("MyFirstModule.predsednik"),
		clan1("MyFirstModule.clan1"),
		clan2("MyFirstModule.clan2");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PopisniDokument(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PopisniDokument(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject popisniDokumentMendixObject)
	{
		if (popisniDokumentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!popisniDokumentMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.popisniDokumentMendixObject = popisniDokumentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.PopisniDokument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.PopisniDokument(context, mendixObject);
	}

	public static myfirstmodule.proxies.PopisniDokument load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.PopisniDokument.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.PopisniDokument> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.PopisniDokument.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of brojPopisa
	 */
	public final java.lang.Integer getbrojPopisa()
	{
		return getbrojPopisa(getContext());
	}

	/**
	 * @param context
	 * @return value of brojPopisa
	 */
	public final java.lang.Integer getbrojPopisa(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.brojPopisa.toString());
	}

	/**
	 * Set value of brojPopisa
	 * @param brojpopisa
	 */
	public final void setbrojPopisa(java.lang.Integer brojpopisa)
	{
		setbrojPopisa(getContext(), brojpopisa);
	}

	/**
	 * Set value of brojPopisa
	 * @param context
	 * @param brojpopisa
	 */
	public final void setbrojPopisa(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer brojpopisa)
	{
		getMendixObject().setValue(context, MemberNames.brojPopisa.toString(), brojpopisa);
	}

	/**
	 * @return value of datumDokumenta
	 */
	public final java.util.Date getdatumDokumenta()
	{
		return getdatumDokumenta(getContext());
	}

	/**
	 * @param context
	 * @return value of datumDokumenta
	 */
	public final java.util.Date getdatumDokumenta(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.datumDokumenta.toString());
	}

	/**
	 * Set value of datumDokumenta
	 * @param datumdokumenta
	 */
	public final void setdatumDokumenta(java.util.Date datumdokumenta)
	{
		setdatumDokumenta(getContext(), datumdokumenta);
	}

	/**
	 * Set value of datumDokumenta
	 * @param context
	 * @param datumdokumenta
	 */
	public final void setdatumDokumenta(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datumdokumenta)
	{
		getMendixObject().setValue(context, MemberNames.datumDokumenta.toString(), datumdokumenta);
	}

	/**
	 * @return value of datumKnjizenja
	 */
	public final java.util.Date getdatumKnjizenja()
	{
		return getdatumKnjizenja(getContext());
	}

	/**
	 * @param context
	 * @return value of datumKnjizenja
	 */
	public final java.util.Date getdatumKnjizenja(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.datumKnjizenja.toString());
	}

	/**
	 * Set value of datumKnjizenja
	 * @param datumknjizenja
	 */
	public final void setdatumKnjizenja(java.util.Date datumknjizenja)
	{
		setdatumKnjizenja(getContext(), datumknjizenja);
	}

	/**
	 * Set value of datumKnjizenja
	 * @param context
	 * @param datumknjizenja
	 */
	public final void setdatumKnjizenja(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datumknjizenja)
	{
		getMendixObject().setValue(context, MemberNames.datumKnjizenja.toString(), datumknjizenja);
	}

	/**
	 * @return value of datumPopisa
	 */
	public final java.util.Date getdatumPopisa()
	{
		return getdatumPopisa(getContext());
	}

	/**
	 * @param context
	 * @return value of datumPopisa
	 */
	public final java.util.Date getdatumPopisa(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.datumPopisa.toString());
	}

	/**
	 * Set value of datumPopisa
	 * @param datumpopisa
	 */
	public final void setdatumPopisa(java.util.Date datumpopisa)
	{
		setdatumPopisa(getContext(), datumpopisa);
	}

	/**
	 * Set value of datumPopisa
	 * @param context
	 * @param datumpopisa
	 */
	public final void setdatumPopisa(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datumpopisa)
	{
		getMendixObject().setValue(context, MemberNames.datumPopisa.toString(), datumpopisa);
	}

	/**
	 * Get value of statusPopisa
	 * @param statuspopisa
	 */
	public final myfirstmodule.proxies.StatusPopisa getstatusPopisa()
	{
		return getstatusPopisa(getContext());
	}

	/**
	 * @param context
	 * @return value of statusPopisa
	 */
	public final myfirstmodule.proxies.StatusPopisa getstatusPopisa(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.statusPopisa.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.StatusPopisa.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of statusPopisa
	 * @param statuspopisa
	 */
	public final void setstatusPopisa(myfirstmodule.proxies.StatusPopisa statuspopisa)
	{
		setstatusPopisa(getContext(), statuspopisa);
	}

	/**
	 * Set value of statusPopisa
	 * @param context
	 * @param statuspopisa
	 */
	public final void setstatusPopisa(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.StatusPopisa statuspopisa)
	{
		if (statuspopisa != null) {
			getMendixObject().setValue(context, MemberNames.statusPopisa.toString(), statuspopisa.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.statusPopisa.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PopisniDokument_Magacin
	 */
	public final myfirstmodule.proxies.Magacin getPopisniDokument_Magacin() throws com.mendix.core.CoreException
	{
		return getPopisniDokument_Magacin(getContext());
	}

	/**
	 * @param context
	 * @return value of PopisniDokument_Magacin
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Magacin getPopisniDokument_Magacin(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Magacin result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PopisniDokument_Magacin.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Magacin.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PopisniDokument_Magacin
	 * @param popisnidokument_magacin
	 */
	public final void setPopisniDokument_Magacin(myfirstmodule.proxies.Magacin popisnidokument_magacin)
	{
		setPopisniDokument_Magacin(getContext(), popisnidokument_magacin);
	}

	/**
	 * Set value of PopisniDokument_Magacin
	 * @param context
	 * @param popisnidokument_magacin
	 */
	public final void setPopisniDokument_Magacin(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Magacin popisnidokument_magacin)
	{
		if (popisnidokument_magacin == null) {
			getMendixObject().setValue(context, MemberNames.PopisniDokument_Magacin.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PopisniDokument_Magacin.toString(), popisnidokument_magacin.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of predsednik
	 */
	public final myfirstmodule.proxies.Radnik getpredsednik() throws com.mendix.core.CoreException
	{
		return getpredsednik(getContext());
	}

	/**
	 * @param context
	 * @return value of predsednik
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Radnik getpredsednik(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Radnik result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.predsednik.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Radnik.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of predsednik
	 * @param predsednik
	 */
	public final void setpredsednik(myfirstmodule.proxies.Radnik predsednik)
	{
		setpredsednik(getContext(), predsednik);
	}

	/**
	 * Set value of predsednik
	 * @param context
	 * @param predsednik
	 */
	public final void setpredsednik(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Radnik predsednik)
	{
		if (predsednik == null) {
			getMendixObject().setValue(context, MemberNames.predsednik.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.predsednik.toString(), predsednik.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of clan1
	 */
	public final myfirstmodule.proxies.Radnik getclan1() throws com.mendix.core.CoreException
	{
		return getclan1(getContext());
	}

	/**
	 * @param context
	 * @return value of clan1
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Radnik getclan1(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Radnik result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.clan1.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Radnik.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of clan1
	 * @param clan1
	 */
	public final void setclan1(myfirstmodule.proxies.Radnik clan1)
	{
		setclan1(getContext(), clan1);
	}

	/**
	 * Set value of clan1
	 * @param context
	 * @param clan1
	 */
	public final void setclan1(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Radnik clan1)
	{
		if (clan1 == null) {
			getMendixObject().setValue(context, MemberNames.clan1.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.clan1.toString(), clan1.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of clan2
	 */
	public final myfirstmodule.proxies.Radnik getclan2() throws com.mendix.core.CoreException
	{
		return getclan2(getContext());
	}

	/**
	 * @param context
	 * @return value of clan2
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Radnik getclan2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Radnik result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.clan2.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Radnik.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of clan2
	 * @param clan2
	 */
	public final void setclan2(myfirstmodule.proxies.Radnik clan2)
	{
		setclan2(getContext(), clan2);
	}

	/**
	 * Set value of clan2
	 * @param context
	 * @param clan2
	 */
	public final void setclan2(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Radnik clan2)
	{
		if (clan2 == null) {
			getMendixObject().setValue(context, MemberNames.clan2.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.clan2.toString(), clan2.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return popisniDokumentMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.PopisniDokument that = (myfirstmodule.proxies.PopisniDokument) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
