// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class PoslovnaGodina implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject poslovnaGodinaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.PoslovnaGodina";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		godina("godina"),
		zakljucena("zakljucena"),
		PoslovnaGodina_Preduzece("MyFirstModule.PoslovnaGodina_Preduzece");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PoslovnaGodina(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PoslovnaGodina(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject poslovnaGodinaMendixObject)
	{
		if (poslovnaGodinaMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!poslovnaGodinaMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.poslovnaGodinaMendixObject = poslovnaGodinaMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.PoslovnaGodina initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.PoslovnaGodina(context, mendixObject);
	}

	public static myfirstmodule.proxies.PoslovnaGodina load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.PoslovnaGodina.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.PoslovnaGodina> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.PoslovnaGodina.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of godina
	 */
	public final java.lang.Integer getgodina()
	{
		return getgodina(getContext());
	}

	/**
	 * @param context
	 * @return value of godina
	 */
	public final java.lang.Integer getgodina(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.godina.toString());
	}

	/**
	 * Set value of godina
	 * @param godina
	 */
	public final void setgodina(java.lang.Integer godina)
	{
		setgodina(getContext(), godina);
	}

	/**
	 * Set value of godina
	 * @param context
	 * @param godina
	 */
	public final void setgodina(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer godina)
	{
		getMendixObject().setValue(context, MemberNames.godina.toString(), godina);
	}

	/**
	 * @return value of zakljucena
	 */
	public final java.lang.Boolean getzakljucena()
	{
		return getzakljucena(getContext());
	}

	/**
	 * @param context
	 * @return value of zakljucena
	 */
	public final java.lang.Boolean getzakljucena(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.zakljucena.toString());
	}

	/**
	 * Set value of zakljucena
	 * @param zakljucena
	 */
	public final void setzakljucena(java.lang.Boolean zakljucena)
	{
		setzakljucena(getContext(), zakljucena);
	}

	/**
	 * Set value of zakljucena
	 * @param context
	 * @param zakljucena
	 */
	public final void setzakljucena(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean zakljucena)
	{
		getMendixObject().setValue(context, MemberNames.zakljucena.toString(), zakljucena);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PoslovnaGodina_Preduzece
	 */
	public final myfirstmodule.proxies.Preduzece getPoslovnaGodina_Preduzece() throws com.mendix.core.CoreException
	{
		return getPoslovnaGodina_Preduzece(getContext());
	}

	/**
	 * @param context
	 * @return value of PoslovnaGodina_Preduzece
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Preduzece getPoslovnaGodina_Preduzece(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Preduzece result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PoslovnaGodina_Preduzece.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Preduzece.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PoslovnaGodina_Preduzece
	 * @param poslovnagodina_preduzece
	 */
	public final void setPoslovnaGodina_Preduzece(myfirstmodule.proxies.Preduzece poslovnagodina_preduzece)
	{
		setPoslovnaGodina_Preduzece(getContext(), poslovnagodina_preduzece);
	}

	/**
	 * Set value of PoslovnaGodina_Preduzece
	 * @param context
	 * @param poslovnagodina_preduzece
	 */
	public final void setPoslovnaGodina_Preduzece(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Preduzece poslovnagodina_preduzece)
	{
		if (poslovnagodina_preduzece == null) {
			getMendixObject().setValue(context, MemberNames.PoslovnaGodina_Preduzece.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PoslovnaGodina_Preduzece.toString(), poslovnagodina_preduzece.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return poslovnaGodinaMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.PoslovnaGodina that = (myfirstmodule.proxies.PoslovnaGodina) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
