// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class PoslovniPartner implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject poslovniPartnerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.PoslovniPartner";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		vrstaPartnera("vrstaPartnera"),
		PoslovniPartner_Preduzece("MyFirstModule.PoslovniPartner_Preduzece"),
		PoslovniPartner_RobaIliUsluga("MyFirstModule.PoslovniPartner_RobaIliUsluga");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PoslovniPartner(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PoslovniPartner(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject poslovniPartnerMendixObject)
	{
		if (poslovniPartnerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!poslovniPartnerMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.poslovniPartnerMendixObject = poslovniPartnerMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.PoslovniPartner initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.PoslovniPartner(context, mendixObject);
	}

	public static myfirstmodule.proxies.PoslovniPartner load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.PoslovniPartner.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.PoslovniPartner> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.PoslovniPartner.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Get value of vrstaPartnera
	 * @param vrstapartnera
	 */
	public final myfirstmodule.proxies.VrstaPartnera getvrstaPartnera()
	{
		return getvrstaPartnera(getContext());
	}

	/**
	 * @param context
	 * @return value of vrstaPartnera
	 */
	public final myfirstmodule.proxies.VrstaPartnera getvrstaPartnera(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.vrstaPartnera.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.VrstaPartnera.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of vrstaPartnera
	 * @param vrstapartnera
	 */
	public final void setvrstaPartnera(myfirstmodule.proxies.VrstaPartnera vrstapartnera)
	{
		setvrstaPartnera(getContext(), vrstapartnera);
	}

	/**
	 * Set value of vrstaPartnera
	 * @param context
	 * @param vrstapartnera
	 */
	public final void setvrstaPartnera(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.VrstaPartnera vrstapartnera)
	{
		if (vrstapartnera != null) {
			getMendixObject().setValue(context, MemberNames.vrstaPartnera.toString(), vrstapartnera.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.vrstaPartnera.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PoslovniPartner_Preduzece
	 */
	public final myfirstmodule.proxies.Preduzece getPoslovniPartner_Preduzece() throws com.mendix.core.CoreException
	{
		return getPoslovniPartner_Preduzece(getContext());
	}

	/**
	 * @param context
	 * @return value of PoslovniPartner_Preduzece
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Preduzece getPoslovniPartner_Preduzece(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Preduzece result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PoslovniPartner_Preduzece.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Preduzece.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PoslovniPartner_Preduzece
	 * @param poslovnipartner_preduzece
	 */
	public final void setPoslovniPartner_Preduzece(myfirstmodule.proxies.Preduzece poslovnipartner_preduzece)
	{
		setPoslovniPartner_Preduzece(getContext(), poslovnipartner_preduzece);
	}

	/**
	 * Set value of PoslovniPartner_Preduzece
	 * @param context
	 * @param poslovnipartner_preduzece
	 */
	public final void setPoslovniPartner_Preduzece(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Preduzece poslovnipartner_preduzece)
	{
		if (poslovnipartner_preduzece == null) {
			getMendixObject().setValue(context, MemberNames.PoslovniPartner_Preduzece.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PoslovniPartner_Preduzece.toString(), poslovnipartner_preduzece.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PoslovniPartner_RobaIliUsluga
	 */
	public final java.util.List<myfirstmodule.proxies.RobaIliUsluga> getPoslovniPartner_RobaIliUsluga() throws com.mendix.core.CoreException
	{
		return getPoslovniPartner_RobaIliUsluga(getContext());
	}

	/**
	 * @param context
	 * @return value of PoslovniPartner_RobaIliUsluga
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.RobaIliUsluga> getPoslovniPartner_RobaIliUsluga(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.RobaIliUsluga> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.PoslovniPartner_RobaIliUsluga.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(myfirstmodule.proxies.RobaIliUsluga.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of PoslovniPartner_RobaIliUsluga
	 * @param poslovnipartner_robailiusluga
	 */
	public final void setPoslovniPartner_RobaIliUsluga(java.util.List<myfirstmodule.proxies.RobaIliUsluga> poslovnipartner_robailiusluga)
	{
		setPoslovniPartner_RobaIliUsluga(getContext(), poslovnipartner_robailiusluga);
	}

	/**
	 * Set value of PoslovniPartner_RobaIliUsluga
	 * @param context
	 * @param poslovnipartner_robailiusluga
	 */
	public final void setPoslovniPartner_RobaIliUsluga(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.RobaIliUsluga> poslovnipartner_robailiusluga)
	{
		var identifiers = poslovnipartner_robailiusluga
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.PoslovniPartner_RobaIliUsluga.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return poslovniPartnerMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.PoslovniPartner that = (myfirstmodule.proxies.PoslovniPartner) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
