// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Preduzece implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject preduzeceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Preduzece";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		nazivPreduzeca("nazivPreduzeca"),
		PIB("PIB"),
		adresaPreduzeca("adresaPreduzeca");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Preduzece(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Preduzece(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject preduzeceMendixObject)
	{
		if (preduzeceMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!preduzeceMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.preduzeceMendixObject = preduzeceMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Preduzece initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Preduzece(context, mendixObject);
	}

	public static myfirstmodule.proxies.Preduzece load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Preduzece.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Preduzece> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Preduzece.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of nazivPreduzeca
	 */
	public final java.lang.String getnazivPreduzeca()
	{
		return getnazivPreduzeca(getContext());
	}

	/**
	 * @param context
	 * @return value of nazivPreduzeca
	 */
	public final java.lang.String getnazivPreduzeca(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.nazivPreduzeca.toString());
	}

	/**
	 * Set value of nazivPreduzeca
	 * @param nazivpreduzeca
	 */
	public final void setnazivPreduzeca(java.lang.String nazivpreduzeca)
	{
		setnazivPreduzeca(getContext(), nazivpreduzeca);
	}

	/**
	 * Set value of nazivPreduzeca
	 * @param context
	 * @param nazivpreduzeca
	 */
	public final void setnazivPreduzeca(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nazivpreduzeca)
	{
		getMendixObject().setValue(context, MemberNames.nazivPreduzeca.toString(), nazivpreduzeca);
	}

	/**
	 * @return value of PIB
	 */
	public final java.lang.String getPIB()
	{
		return getPIB(getContext());
	}

	/**
	 * @param context
	 * @return value of PIB
	 */
	public final java.lang.String getPIB(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PIB.toString());
	}

	/**
	 * Set value of PIB
	 * @param pib
	 */
	public final void setPIB(java.lang.String pib)
	{
		setPIB(getContext(), pib);
	}

	/**
	 * Set value of PIB
	 * @param context
	 * @param pib
	 */
	public final void setPIB(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pib)
	{
		getMendixObject().setValue(context, MemberNames.PIB.toString(), pib);
	}

	/**
	 * @return value of adresaPreduzeca
	 */
	public final java.lang.String getadresaPreduzeca()
	{
		return getadresaPreduzeca(getContext());
	}

	/**
	 * @param context
	 * @return value of adresaPreduzeca
	 */
	public final java.lang.String getadresaPreduzeca(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.adresaPreduzeca.toString());
	}

	/**
	 * Set value of adresaPreduzeca
	 * @param adresapreduzeca
	 */
	public final void setadresaPreduzeca(java.lang.String adresapreduzeca)
	{
		setadresaPreduzeca(getContext(), adresapreduzeca);
	}

	/**
	 * Set value of adresaPreduzeca
	 * @param context
	 * @param adresapreduzeca
	 */
	public final void setadresaPreduzeca(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String adresapreduzeca)
	{
		getMendixObject().setValue(context, MemberNames.adresaPreduzeca.toString(), adresapreduzeca);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return preduzeceMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Preduzece that = (myfirstmodule.proxies.Preduzece) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
