// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class PrometRobneKartice implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject prometRobneKarticeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.PrometRobneKartice";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		vrstaPrometa("vrstaPrometa"),
		kolicina("kolicina"),
		smerPrometa("smerPrometa"),
		cena("cena"),
		vrednost("vrednost"),
		napomena("napomena"),
		datumPrometa("datumPrometa"),
		PrometRobneKartice_RobnaKartica("MyFirstModule.PrometRobneKartice_RobnaKartica");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PrometRobneKartice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PrometRobneKartice(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject prometRobneKarticeMendixObject)
	{
		if (prometRobneKarticeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!prometRobneKarticeMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.prometRobneKarticeMendixObject = prometRobneKarticeMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.PrometRobneKartice initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.PrometRobneKartice(context, mendixObject);
	}

	public static myfirstmodule.proxies.PrometRobneKartice load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.PrometRobneKartice.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.PrometRobneKartice> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.PrometRobneKartice.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Get value of vrstaPrometa
	 * @param vrstaprometa
	 */
	public final myfirstmodule.proxies.VrstaPrometa getvrstaPrometa()
	{
		return getvrstaPrometa(getContext());
	}

	/**
	 * @param context
	 * @return value of vrstaPrometa
	 */
	public final myfirstmodule.proxies.VrstaPrometa getvrstaPrometa(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.vrstaPrometa.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.VrstaPrometa.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of vrstaPrometa
	 * @param vrstaprometa
	 */
	public final void setvrstaPrometa(myfirstmodule.proxies.VrstaPrometa vrstaprometa)
	{
		setvrstaPrometa(getContext(), vrstaprometa);
	}

	/**
	 * Set value of vrstaPrometa
	 * @param context
	 * @param vrstaprometa
	 */
	public final void setvrstaPrometa(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.VrstaPrometa vrstaprometa)
	{
		if (vrstaprometa != null) {
			getMendixObject().setValue(context, MemberNames.vrstaPrometa.toString(), vrstaprometa.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.vrstaPrometa.toString(), null);
		}
	}

	/**
	 * @return value of kolicina
	 */
	public final java.lang.Integer getkolicina()
	{
		return getkolicina(getContext());
	}

	/**
	 * @param context
	 * @return value of kolicina
	 */
	public final java.lang.Integer getkolicina(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.kolicina.toString());
	}

	/**
	 * Set value of kolicina
	 * @param kolicina
	 */
	public final void setkolicina(java.lang.Integer kolicina)
	{
		setkolicina(getContext(), kolicina);
	}

	/**
	 * Set value of kolicina
	 * @param context
	 * @param kolicina
	 */
	public final void setkolicina(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer kolicina)
	{
		getMendixObject().setValue(context, MemberNames.kolicina.toString(), kolicina);
	}

	/**
	 * Get value of smerPrometa
	 * @param smerprometa
	 */
	public final myfirstmodule.proxies.SmerPrometa getsmerPrometa()
	{
		return getsmerPrometa(getContext());
	}

	/**
	 * @param context
	 * @return value of smerPrometa
	 */
	public final myfirstmodule.proxies.SmerPrometa getsmerPrometa(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.smerPrometa.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.SmerPrometa.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of smerPrometa
	 * @param smerprometa
	 */
	public final void setsmerPrometa(myfirstmodule.proxies.SmerPrometa smerprometa)
	{
		setsmerPrometa(getContext(), smerprometa);
	}

	/**
	 * Set value of smerPrometa
	 * @param context
	 * @param smerprometa
	 */
	public final void setsmerPrometa(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.SmerPrometa smerprometa)
	{
		if (smerprometa != null) {
			getMendixObject().setValue(context, MemberNames.smerPrometa.toString(), smerprometa.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.smerPrometa.toString(), null);
		}
	}

	/**
	 * @return value of cena
	 */
	public final java.lang.Integer getcena()
	{
		return getcena(getContext());
	}

	/**
	 * @param context
	 * @return value of cena
	 */
	public final java.lang.Integer getcena(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.cena.toString());
	}

	/**
	 * Set value of cena
	 * @param cena
	 */
	public final void setcena(java.lang.Integer cena)
	{
		setcena(getContext(), cena);
	}

	/**
	 * Set value of cena
	 * @param context
	 * @param cena
	 */
	public final void setcena(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer cena)
	{
		getMendixObject().setValue(context, MemberNames.cena.toString(), cena);
	}

	/**
	 * @return value of vrednost
	 */
	public final java.lang.Integer getvrednost()
	{
		return getvrednost(getContext());
	}

	/**
	 * @param context
	 * @return value of vrednost
	 */
	public final java.lang.Integer getvrednost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.vrednost.toString());
	}

	/**
	 * Set value of vrednost
	 * @param vrednost
	 */
	public final void setvrednost(java.lang.Integer vrednost)
	{
		setvrednost(getContext(), vrednost);
	}

	/**
	 * Set value of vrednost
	 * @param context
	 * @param vrednost
	 */
	public final void setvrednost(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer vrednost)
	{
		getMendixObject().setValue(context, MemberNames.vrednost.toString(), vrednost);
	}

	/**
	 * @return value of napomena
	 */
	public final java.lang.String getnapomena()
	{
		return getnapomena(getContext());
	}

	/**
	 * @param context
	 * @return value of napomena
	 */
	public final java.lang.String getnapomena(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.napomena.toString());
	}

	/**
	 * Set value of napomena
	 * @param napomena
	 */
	public final void setnapomena(java.lang.String napomena)
	{
		setnapomena(getContext(), napomena);
	}

	/**
	 * Set value of napomena
	 * @param context
	 * @param napomena
	 */
	public final void setnapomena(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String napomena)
	{
		getMendixObject().setValue(context, MemberNames.napomena.toString(), napomena);
	}

	/**
	 * @return value of datumPrometa
	 */
	public final java.util.Date getdatumPrometa()
	{
		return getdatumPrometa(getContext());
	}

	/**
	 * @param context
	 * @return value of datumPrometa
	 */
	public final java.util.Date getdatumPrometa(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.datumPrometa.toString());
	}

	/**
	 * Set value of datumPrometa
	 * @param datumprometa
	 */
	public final void setdatumPrometa(java.util.Date datumprometa)
	{
		setdatumPrometa(getContext(), datumprometa);
	}

	/**
	 * Set value of datumPrometa
	 * @param context
	 * @param datumprometa
	 */
	public final void setdatumPrometa(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datumprometa)
	{
		getMendixObject().setValue(context, MemberNames.datumPrometa.toString(), datumprometa);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PrometRobneKartice_RobnaKartica
	 */
	public final myfirstmodule.proxies.RobnaKartica getPrometRobneKartice_RobnaKartica() throws com.mendix.core.CoreException
	{
		return getPrometRobneKartice_RobnaKartica(getContext());
	}

	/**
	 * @param context
	 * @return value of PrometRobneKartice_RobnaKartica
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.RobnaKartica getPrometRobneKartice_RobnaKartica(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.RobnaKartica result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PrometRobneKartice_RobnaKartica.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.RobnaKartica.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PrometRobneKartice_RobnaKartica
	 * @param prometrobnekartice_robnakartica
	 */
	public final void setPrometRobneKartice_RobnaKartica(myfirstmodule.proxies.RobnaKartica prometrobnekartice_robnakartica)
	{
		setPrometRobneKartice_RobnaKartica(getContext(), prometrobnekartice_robnakartica);
	}

	/**
	 * Set value of PrometRobneKartice_RobnaKartica
	 * @param context
	 * @param prometrobnekartice_robnakartica
	 */
	public final void setPrometRobneKartice_RobnaKartica(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.RobnaKartica prometrobnekartice_robnakartica)
	{
		if (prometrobnekartice_robnakartica == null) {
			getMendixObject().setValue(context, MemberNames.PrometRobneKartice_RobnaKartica.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PrometRobneKartice_RobnaKartica.toString(), prometrobnekartice_robnakartica.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return prometRobneKarticeMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.PrometRobneKartice that = (myfirstmodule.proxies.PrometRobneKartice) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
