// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class PrometniDokument implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject prometniDokumentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.PrometniDokument";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		broj("broj"),
		datumDokumenta("datumDokumenta"),
		datumKnjizenja("datumKnjizenja"),
		status("status"),
		vrstaDokumenta("vrstaDokumenta"),
		PrometniDokument_PoslovnaGodina("MyFirstModule.PrometniDokument_PoslovnaGodina"),
		PrometniDokument_Magacin("MyFirstModule.PrometniDokument_Magacin"),
		PrometniDokument_Magacin_2("MyFirstModule.PrometniDokument_Magacin_2"),
		PrometniDokument_PoslovniPartner("MyFirstModule.PrometniDokument_PoslovniPartner"),
		PrometniDokument_IzlaznaFaktura("MyFirstModule.PrometniDokument_IzlaznaFaktura");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PrometniDokument(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PrometniDokument(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject prometniDokumentMendixObject)
	{
		if (prometniDokumentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!prometniDokumentMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.prometniDokumentMendixObject = prometniDokumentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.PrometniDokument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.PrometniDokument(context, mendixObject);
	}

	public static myfirstmodule.proxies.PrometniDokument load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.PrometniDokument.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.PrometniDokument> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.PrometniDokument.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of broj
	 */
	public final java.lang.Integer getbroj()
	{
		return getbroj(getContext());
	}

	/**
	 * @param context
	 * @return value of broj
	 */
	public final java.lang.Integer getbroj(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.broj.toString());
	}

	/**
	 * Set value of broj
	 * @param broj
	 */
	public final void setbroj(java.lang.Integer broj)
	{
		setbroj(getContext(), broj);
	}

	/**
	 * Set value of broj
	 * @param context
	 * @param broj
	 */
	public final void setbroj(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer broj)
	{
		getMendixObject().setValue(context, MemberNames.broj.toString(), broj);
	}

	/**
	 * @return value of datumDokumenta
	 */
	public final java.util.Date getdatumDokumenta()
	{
		return getdatumDokumenta(getContext());
	}

	/**
	 * @param context
	 * @return value of datumDokumenta
	 */
	public final java.util.Date getdatumDokumenta(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.datumDokumenta.toString());
	}

	/**
	 * Set value of datumDokumenta
	 * @param datumdokumenta
	 */
	public final void setdatumDokumenta(java.util.Date datumdokumenta)
	{
		setdatumDokumenta(getContext(), datumdokumenta);
	}

	/**
	 * Set value of datumDokumenta
	 * @param context
	 * @param datumdokumenta
	 */
	public final void setdatumDokumenta(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datumdokumenta)
	{
		getMendixObject().setValue(context, MemberNames.datumDokumenta.toString(), datumdokumenta);
	}

	/**
	 * @return value of datumKnjizenja
	 */
	public final java.util.Date getdatumKnjizenja()
	{
		return getdatumKnjizenja(getContext());
	}

	/**
	 * @param context
	 * @return value of datumKnjizenja
	 */
	public final java.util.Date getdatumKnjizenja(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.datumKnjizenja.toString());
	}

	/**
	 * Set value of datumKnjizenja
	 * @param datumknjizenja
	 */
	public final void setdatumKnjizenja(java.util.Date datumknjizenja)
	{
		setdatumKnjizenja(getContext(), datumknjizenja);
	}

	/**
	 * Set value of datumKnjizenja
	 * @param context
	 * @param datumknjizenja
	 */
	public final void setdatumKnjizenja(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datumknjizenja)
	{
		getMendixObject().setValue(context, MemberNames.datumKnjizenja.toString(), datumknjizenja);
	}

	/**
	 * Get value of status
	 * @param status
	 */
	public final myfirstmodule.proxies.StatusDokumenta getstatus()
	{
		return getstatus(getContext());
	}

	/**
	 * @param context
	 * @return value of status
	 */
	public final myfirstmodule.proxies.StatusDokumenta getstatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.status.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.StatusDokumenta.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of status
	 * @param status
	 */
	public final void setstatus(myfirstmodule.proxies.StatusDokumenta status)
	{
		setstatus(getContext(), status);
	}

	/**
	 * Set value of status
	 * @param context
	 * @param status
	 */
	public final void setstatus(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.StatusDokumenta status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.status.toString(), null);
		}
	}

	/**
	 * Get value of vrstaDokumenta
	 * @param vrstadokumenta
	 */
	public final myfirstmodule.proxies.VrstaPrometnogDokumenta getvrstaDokumenta()
	{
		return getvrstaDokumenta(getContext());
	}

	/**
	 * @param context
	 * @return value of vrstaDokumenta
	 */
	public final myfirstmodule.proxies.VrstaPrometnogDokumenta getvrstaDokumenta(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.vrstaDokumenta.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.VrstaPrometnogDokumenta.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of vrstaDokumenta
	 * @param vrstadokumenta
	 */
	public final void setvrstaDokumenta(myfirstmodule.proxies.VrstaPrometnogDokumenta vrstadokumenta)
	{
		setvrstaDokumenta(getContext(), vrstadokumenta);
	}

	/**
	 * Set value of vrstaDokumenta
	 * @param context
	 * @param vrstadokumenta
	 */
	public final void setvrstaDokumenta(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.VrstaPrometnogDokumenta vrstadokumenta)
	{
		if (vrstadokumenta != null) {
			getMendixObject().setValue(context, MemberNames.vrstaDokumenta.toString(), vrstadokumenta.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.vrstaDokumenta.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PrometniDokument_PoslovnaGodina
	 */
	public final myfirstmodule.proxies.PoslovnaGodina getPrometniDokument_PoslovnaGodina() throws com.mendix.core.CoreException
	{
		return getPrometniDokument_PoslovnaGodina(getContext());
	}

	/**
	 * @param context
	 * @return value of PrometniDokument_PoslovnaGodina
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.PoslovnaGodina getPrometniDokument_PoslovnaGodina(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.PoslovnaGodina result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PrometniDokument_PoslovnaGodina.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.PoslovnaGodina.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PrometniDokument_PoslovnaGodina
	 * @param prometnidokument_poslovnagodina
	 */
	public final void setPrometniDokument_PoslovnaGodina(myfirstmodule.proxies.PoslovnaGodina prometnidokument_poslovnagodina)
	{
		setPrometniDokument_PoslovnaGodina(getContext(), prometnidokument_poslovnagodina);
	}

	/**
	 * Set value of PrometniDokument_PoslovnaGodina
	 * @param context
	 * @param prometnidokument_poslovnagodina
	 */
	public final void setPrometniDokument_PoslovnaGodina(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.PoslovnaGodina prometnidokument_poslovnagodina)
	{
		if (prometnidokument_poslovnagodina == null) {
			getMendixObject().setValue(context, MemberNames.PrometniDokument_PoslovnaGodina.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PrometniDokument_PoslovnaGodina.toString(), prometnidokument_poslovnagodina.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PrometniDokument_Magacin
	 */
	public final myfirstmodule.proxies.Magacin getPrometniDokument_Magacin() throws com.mendix.core.CoreException
	{
		return getPrometniDokument_Magacin(getContext());
	}

	/**
	 * @param context
	 * @return value of PrometniDokument_Magacin
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Magacin getPrometniDokument_Magacin(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Magacin result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PrometniDokument_Magacin.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Magacin.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PrometniDokument_Magacin
	 * @param prometnidokument_magacin
	 */
	public final void setPrometniDokument_Magacin(myfirstmodule.proxies.Magacin prometnidokument_magacin)
	{
		setPrometniDokument_Magacin(getContext(), prometnidokument_magacin);
	}

	/**
	 * Set value of PrometniDokument_Magacin
	 * @param context
	 * @param prometnidokument_magacin
	 */
	public final void setPrometniDokument_Magacin(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Magacin prometnidokument_magacin)
	{
		if (prometnidokument_magacin == null) {
			getMendixObject().setValue(context, MemberNames.PrometniDokument_Magacin.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PrometniDokument_Magacin.toString(), prometnidokument_magacin.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PrometniDokument_Magacin_2
	 */
	public final myfirstmodule.proxies.Magacin getPrometniDokument_Magacin_2() throws com.mendix.core.CoreException
	{
		return getPrometniDokument_Magacin_2(getContext());
	}

	/**
	 * @param context
	 * @return value of PrometniDokument_Magacin_2
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Magacin getPrometniDokument_Magacin_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Magacin result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PrometniDokument_Magacin_2.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Magacin.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PrometniDokument_Magacin_2
	 * @param prometnidokument_magacin_2
	 */
	public final void setPrometniDokument_Magacin_2(myfirstmodule.proxies.Magacin prometnidokument_magacin_2)
	{
		setPrometniDokument_Magacin_2(getContext(), prometnidokument_magacin_2);
	}

	/**
	 * Set value of PrometniDokument_Magacin_2
	 * @param context
	 * @param prometnidokument_magacin_2
	 */
	public final void setPrometniDokument_Magacin_2(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Magacin prometnidokument_magacin_2)
	{
		if (prometnidokument_magacin_2 == null) {
			getMendixObject().setValue(context, MemberNames.PrometniDokument_Magacin_2.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PrometniDokument_Magacin_2.toString(), prometnidokument_magacin_2.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PrometniDokument_PoslovniPartner
	 */
	public final myfirstmodule.proxies.PoslovniPartner getPrometniDokument_PoslovniPartner() throws com.mendix.core.CoreException
	{
		return getPrometniDokument_PoslovniPartner(getContext());
	}

	/**
	 * @param context
	 * @return value of PrometniDokument_PoslovniPartner
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.PoslovniPartner getPrometniDokument_PoslovniPartner(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.PoslovniPartner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PrometniDokument_PoslovniPartner.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.PoslovniPartner.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PrometniDokument_PoslovniPartner
	 * @param prometnidokument_poslovnipartner
	 */
	public final void setPrometniDokument_PoslovniPartner(myfirstmodule.proxies.PoslovniPartner prometnidokument_poslovnipartner)
	{
		setPrometniDokument_PoslovniPartner(getContext(), prometnidokument_poslovnipartner);
	}

	/**
	 * Set value of PrometniDokument_PoslovniPartner
	 * @param context
	 * @param prometnidokument_poslovnipartner
	 */
	public final void setPrometniDokument_PoslovniPartner(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.PoslovniPartner prometnidokument_poslovnipartner)
	{
		if (prometnidokument_poslovnipartner == null) {
			getMendixObject().setValue(context, MemberNames.PrometniDokument_PoslovniPartner.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PrometniDokument_PoslovniPartner.toString(), prometnidokument_poslovnipartner.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PrometniDokument_IzlaznaFaktura
	 */
	public final prodaja.proxies.IzlaznaFaktura getPrometniDokument_IzlaznaFaktura() throws com.mendix.core.CoreException
	{
		return getPrometniDokument_IzlaznaFaktura(getContext());
	}

	/**
	 * @param context
	 * @return value of PrometniDokument_IzlaznaFaktura
	 * @throws com.mendix.core.CoreException
	 */
	public final prodaja.proxies.IzlaznaFaktura getPrometniDokument_IzlaznaFaktura(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		prodaja.proxies.IzlaznaFaktura result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PrometniDokument_IzlaznaFaktura.toString());
		if (identifier != null) {
			result = prodaja.proxies.IzlaznaFaktura.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PrometniDokument_IzlaznaFaktura
	 * @param prometnidokument_izlaznafaktura
	 */
	public final void setPrometniDokument_IzlaznaFaktura(prodaja.proxies.IzlaznaFaktura prometnidokument_izlaznafaktura)
	{
		setPrometniDokument_IzlaznaFaktura(getContext(), prometnidokument_izlaznafaktura);
	}

	/**
	 * Set value of PrometniDokument_IzlaznaFaktura
	 * @param context
	 * @param prometnidokument_izlaznafaktura
	 */
	public final void setPrometniDokument_IzlaznaFaktura(com.mendix.systemwideinterfaces.core.IContext context, prodaja.proxies.IzlaznaFaktura prometnidokument_izlaznafaktura)
	{
		if (prometnidokument_izlaznafaktura == null) {
			getMendixObject().setValue(context, MemberNames.PrometniDokument_IzlaznaFaktura.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PrometniDokument_IzlaznaFaktura.toString(), prometnidokument_izlaznafaktura.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return prometniDokumentMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.PrometniDokument that = (myfirstmodule.proxies.PrometniDokument) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
