// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Radnik implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject radnikMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Radnik";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Ime("Ime"),
		Prezime("Prezime"),
		Radnik_Preduzece("MyFirstModule.Radnik_Preduzece");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Radnik(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Radnik(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject radnikMendixObject)
	{
		if (radnikMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!radnikMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.radnikMendixObject = radnikMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Radnik initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Radnik(context, mendixObject);
	}

	public static myfirstmodule.proxies.Radnik load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Radnik.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Radnik> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Radnik.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Ime
	 */
	public final java.lang.String getIme()
	{
		return getIme(getContext());
	}

	/**
	 * @param context
	 * @return value of Ime
	 */
	public final java.lang.String getIme(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Ime.toString());
	}

	/**
	 * Set value of Ime
	 * @param ime
	 */
	public final void setIme(java.lang.String ime)
	{
		setIme(getContext(), ime);
	}

	/**
	 * Set value of Ime
	 * @param context
	 * @param ime
	 */
	public final void setIme(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ime)
	{
		getMendixObject().setValue(context, MemberNames.Ime.toString(), ime);
	}

	/**
	 * @return value of Prezime
	 */
	public final java.lang.String getPrezime()
	{
		return getPrezime(getContext());
	}

	/**
	 * @param context
	 * @return value of Prezime
	 */
	public final java.lang.String getPrezime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Prezime.toString());
	}

	/**
	 * Set value of Prezime
	 * @param prezime
	 */
	public final void setPrezime(java.lang.String prezime)
	{
		setPrezime(getContext(), prezime);
	}

	/**
	 * Set value of Prezime
	 * @param context
	 * @param prezime
	 */
	public final void setPrezime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String prezime)
	{
		getMendixObject().setValue(context, MemberNames.Prezime.toString(), prezime);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Radnik_Preduzece
	 */
	public final myfirstmodule.proxies.Preduzece getRadnik_Preduzece() throws com.mendix.core.CoreException
	{
		return getRadnik_Preduzece(getContext());
	}

	/**
	 * @param context
	 * @return value of Radnik_Preduzece
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Preduzece getRadnik_Preduzece(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Preduzece result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Radnik_Preduzece.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Preduzece.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Radnik_Preduzece
	 * @param radnik_preduzece
	 */
	public final void setRadnik_Preduzece(myfirstmodule.proxies.Preduzece radnik_preduzece)
	{
		setRadnik_Preduzece(getContext(), radnik_preduzece);
	}

	/**
	 * Set value of Radnik_Preduzece
	 * @param context
	 * @param radnik_preduzece
	 */
	public final void setRadnik_Preduzece(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Preduzece radnik_preduzece)
	{
		if (radnik_preduzece == null) {
			getMendixObject().setValue(context, MemberNames.Radnik_Preduzece.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Radnik_Preduzece.toString(), radnik_preduzece.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return radnikMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Radnik that = (myfirstmodule.proxies.Radnik) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
