// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class RobaIliUsluga implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject robaIliUslugaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.RobaIliUsluga";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		naziv("naziv"),
		opis("opis"),
		roba("roba"),
		RobaIliUsluga_JedinicaMere("MyFirstModule.RobaIliUsluga_JedinicaMere"),
		RobaIliUsluga_KategorijaRobe("MyFirstModule.RobaIliUsluga_KategorijaRobe");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RobaIliUsluga(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RobaIliUsluga(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject robaIliUslugaMendixObject)
	{
		if (robaIliUslugaMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!robaIliUslugaMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.robaIliUslugaMendixObject = robaIliUslugaMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.RobaIliUsluga initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.RobaIliUsluga(context, mendixObject);
	}

	public static myfirstmodule.proxies.RobaIliUsluga load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.RobaIliUsluga.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.RobaIliUsluga> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.RobaIliUsluga.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of naziv
	 */
	public final java.lang.String getnaziv()
	{
		return getnaziv(getContext());
	}

	/**
	 * @param context
	 * @return value of naziv
	 */
	public final java.lang.String getnaziv(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.naziv.toString());
	}

	/**
	 * Set value of naziv
	 * @param naziv
	 */
	public final void setnaziv(java.lang.String naziv)
	{
		setnaziv(getContext(), naziv);
	}

	/**
	 * Set value of naziv
	 * @param context
	 * @param naziv
	 */
	public final void setnaziv(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String naziv)
	{
		getMendixObject().setValue(context, MemberNames.naziv.toString(), naziv);
	}

	/**
	 * @return value of opis
	 */
	public final java.lang.String getopis()
	{
		return getopis(getContext());
	}

	/**
	 * @param context
	 * @return value of opis
	 */
	public final java.lang.String getopis(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.opis.toString());
	}

	/**
	 * Set value of opis
	 * @param opis
	 */
	public final void setopis(java.lang.String opis)
	{
		setopis(getContext(), opis);
	}

	/**
	 * Set value of opis
	 * @param context
	 * @param opis
	 */
	public final void setopis(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String opis)
	{
		getMendixObject().setValue(context, MemberNames.opis.toString(), opis);
	}

	/**
	 * @return value of roba
	 */
	public final java.lang.Boolean getroba()
	{
		return getroba(getContext());
	}

	/**
	 * @param context
	 * @return value of roba
	 */
	public final java.lang.Boolean getroba(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.roba.toString());
	}

	/**
	 * Set value of roba
	 * @param roba
	 */
	public final void setroba(java.lang.Boolean roba)
	{
		setroba(getContext(), roba);
	}

	/**
	 * Set value of roba
	 * @param context
	 * @param roba
	 */
	public final void setroba(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean roba)
	{
		getMendixObject().setValue(context, MemberNames.roba.toString(), roba);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RobaIliUsluga_JedinicaMere
	 */
	public final myfirstmodule.proxies.JedinicaMere getRobaIliUsluga_JedinicaMere() throws com.mendix.core.CoreException
	{
		return getRobaIliUsluga_JedinicaMere(getContext());
	}

	/**
	 * @param context
	 * @return value of RobaIliUsluga_JedinicaMere
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.JedinicaMere getRobaIliUsluga_JedinicaMere(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.JedinicaMere result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RobaIliUsluga_JedinicaMere.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.JedinicaMere.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RobaIliUsluga_JedinicaMere
	 * @param robailiusluga_jedinicamere
	 */
	public final void setRobaIliUsluga_JedinicaMere(myfirstmodule.proxies.JedinicaMere robailiusluga_jedinicamere)
	{
		setRobaIliUsluga_JedinicaMere(getContext(), robailiusluga_jedinicamere);
	}

	/**
	 * Set value of RobaIliUsluga_JedinicaMere
	 * @param context
	 * @param robailiusluga_jedinicamere
	 */
	public final void setRobaIliUsluga_JedinicaMere(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.JedinicaMere robailiusluga_jedinicamere)
	{
		if (robailiusluga_jedinicamere == null) {
			getMendixObject().setValue(context, MemberNames.RobaIliUsluga_JedinicaMere.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RobaIliUsluga_JedinicaMere.toString(), robailiusluga_jedinicamere.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RobaIliUsluga_KategorijaRobe
	 */
	public final prodaja.proxies.KategorijaRobe getRobaIliUsluga_KategorijaRobe() throws com.mendix.core.CoreException
	{
		return getRobaIliUsluga_KategorijaRobe(getContext());
	}

	/**
	 * @param context
	 * @return value of RobaIliUsluga_KategorijaRobe
	 * @throws com.mendix.core.CoreException
	 */
	public final prodaja.proxies.KategorijaRobe getRobaIliUsluga_KategorijaRobe(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		prodaja.proxies.KategorijaRobe result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RobaIliUsluga_KategorijaRobe.toString());
		if (identifier != null) {
			result = prodaja.proxies.KategorijaRobe.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RobaIliUsluga_KategorijaRobe
	 * @param robailiusluga_kategorijarobe
	 */
	public final void setRobaIliUsluga_KategorijaRobe(prodaja.proxies.KategorijaRobe robailiusluga_kategorijarobe)
	{
		setRobaIliUsluga_KategorijaRobe(getContext(), robailiusluga_kategorijarobe);
	}

	/**
	 * Set value of RobaIliUsluga_KategorijaRobe
	 * @param context
	 * @param robailiusluga_kategorijarobe
	 */
	public final void setRobaIliUsluga_KategorijaRobe(com.mendix.systemwideinterfaces.core.IContext context, prodaja.proxies.KategorijaRobe robailiusluga_kategorijarobe)
	{
		if (robailiusluga_kategorijarobe == null) {
			getMendixObject().setValue(context, MemberNames.RobaIliUsluga_KategorijaRobe.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RobaIliUsluga_KategorijaRobe.toString(), robailiusluga_kategorijarobe.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return robaIliUslugaMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.RobaIliUsluga that = (myfirstmodule.proxies.RobaIliUsluga) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
