// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class RobnaKartica implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject robnaKarticaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.RobnaKartica";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		pocStanjeKolicina("pocStanjeKolicina"),
		prometUlazaKolicina("prometUlazaKolicina"),
		prometIzlazaKolicina("prometIzlazaKolicina"),
		ukupnaKolicina("ukupnaKolicina"),
		pocStanjeVrednost("pocStanjeVrednost"),
		prometUlazaVrednost("prometUlazaVrednost"),
		prometIzlazaVrednost("prometIzlazaVrednost"),
		ukupnaVrednost("ukupnaVrednost"),
		cena("cena"),
		RobnaKartica_Magacin("MyFirstModule.RobnaKartica_Magacin"),
		RobnaKartica_RobaIliUsluga("MyFirstModule.RobnaKartica_RobaIliUsluga"),
		RobnaKartica_PoslovnaGodina("MyFirstModule.RobnaKartica_PoslovnaGodina");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RobnaKartica(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RobnaKartica(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject robnaKarticaMendixObject)
	{
		if (robnaKarticaMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!robnaKarticaMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.robnaKarticaMendixObject = robnaKarticaMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.RobnaKartica initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.RobnaKartica(context, mendixObject);
	}

	public static myfirstmodule.proxies.RobnaKartica load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.RobnaKartica.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.RobnaKartica> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.RobnaKartica.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of pocStanjeKolicina
	 */
	public final java.math.BigDecimal getpocStanjeKolicina()
	{
		return getpocStanjeKolicina(getContext());
	}

	/**
	 * @param context
	 * @return value of pocStanjeKolicina
	 */
	public final java.math.BigDecimal getpocStanjeKolicina(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.pocStanjeKolicina.toString());
	}

	/**
	 * Set value of pocStanjeKolicina
	 * @param pocstanjekolicina
	 */
	public final void setpocStanjeKolicina(java.math.BigDecimal pocstanjekolicina)
	{
		setpocStanjeKolicina(getContext(), pocstanjekolicina);
	}

	/**
	 * Set value of pocStanjeKolicina
	 * @param context
	 * @param pocstanjekolicina
	 */
	public final void setpocStanjeKolicina(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal pocstanjekolicina)
	{
		getMendixObject().setValue(context, MemberNames.pocStanjeKolicina.toString(), pocstanjekolicina);
	}

	/**
	 * @return value of prometUlazaKolicina
	 */
	public final java.math.BigDecimal getprometUlazaKolicina()
	{
		return getprometUlazaKolicina(getContext());
	}

	/**
	 * @param context
	 * @return value of prometUlazaKolicina
	 */
	public final java.math.BigDecimal getprometUlazaKolicina(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.prometUlazaKolicina.toString());
	}

	/**
	 * Set value of prometUlazaKolicina
	 * @param prometulazakolicina
	 */
	public final void setprometUlazaKolicina(java.math.BigDecimal prometulazakolicina)
	{
		setprometUlazaKolicina(getContext(), prometulazakolicina);
	}

	/**
	 * Set value of prometUlazaKolicina
	 * @param context
	 * @param prometulazakolicina
	 */
	public final void setprometUlazaKolicina(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal prometulazakolicina)
	{
		getMendixObject().setValue(context, MemberNames.prometUlazaKolicina.toString(), prometulazakolicina);
	}

	/**
	 * @return value of prometIzlazaKolicina
	 */
	public final java.math.BigDecimal getprometIzlazaKolicina()
	{
		return getprometIzlazaKolicina(getContext());
	}

	/**
	 * @param context
	 * @return value of prometIzlazaKolicina
	 */
	public final java.math.BigDecimal getprometIzlazaKolicina(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.prometIzlazaKolicina.toString());
	}

	/**
	 * Set value of prometIzlazaKolicina
	 * @param prometizlazakolicina
	 */
	public final void setprometIzlazaKolicina(java.math.BigDecimal prometizlazakolicina)
	{
		setprometIzlazaKolicina(getContext(), prometizlazakolicina);
	}

	/**
	 * Set value of prometIzlazaKolicina
	 * @param context
	 * @param prometizlazakolicina
	 */
	public final void setprometIzlazaKolicina(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal prometizlazakolicina)
	{
		getMendixObject().setValue(context, MemberNames.prometIzlazaKolicina.toString(), prometizlazakolicina);
	}

	/**
	 * @return value of ukupnaKolicina
	 */
	public final java.math.BigDecimal getukupnaKolicina()
	{
		return getukupnaKolicina(getContext());
	}

	/**
	 * @param context
	 * @return value of ukupnaKolicina
	 */
	public final java.math.BigDecimal getukupnaKolicina(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ukupnaKolicina.toString());
	}

	/**
	 * Set value of ukupnaKolicina
	 * @param ukupnakolicina
	 */
	public final void setukupnaKolicina(java.math.BigDecimal ukupnakolicina)
	{
		setukupnaKolicina(getContext(), ukupnakolicina);
	}

	/**
	 * Set value of ukupnaKolicina
	 * @param context
	 * @param ukupnakolicina
	 */
	public final void setukupnaKolicina(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ukupnakolicina)
	{
		getMendixObject().setValue(context, MemberNames.ukupnaKolicina.toString(), ukupnakolicina);
	}

	/**
	 * @return value of pocStanjeVrednost
	 */
	public final java.math.BigDecimal getpocStanjeVrednost()
	{
		return getpocStanjeVrednost(getContext());
	}

	/**
	 * @param context
	 * @return value of pocStanjeVrednost
	 */
	public final java.math.BigDecimal getpocStanjeVrednost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.pocStanjeVrednost.toString());
	}

	/**
	 * Set value of pocStanjeVrednost
	 * @param pocstanjevrednost
	 */
	public final void setpocStanjeVrednost(java.math.BigDecimal pocstanjevrednost)
	{
		setpocStanjeVrednost(getContext(), pocstanjevrednost);
	}

	/**
	 * Set value of pocStanjeVrednost
	 * @param context
	 * @param pocstanjevrednost
	 */
	public final void setpocStanjeVrednost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal pocstanjevrednost)
	{
		getMendixObject().setValue(context, MemberNames.pocStanjeVrednost.toString(), pocstanjevrednost);
	}

	/**
	 * @return value of prometUlazaVrednost
	 */
	public final java.math.BigDecimal getprometUlazaVrednost()
	{
		return getprometUlazaVrednost(getContext());
	}

	/**
	 * @param context
	 * @return value of prometUlazaVrednost
	 */
	public final java.math.BigDecimal getprometUlazaVrednost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.prometUlazaVrednost.toString());
	}

	/**
	 * Set value of prometUlazaVrednost
	 * @param prometulazavrednost
	 */
	public final void setprometUlazaVrednost(java.math.BigDecimal prometulazavrednost)
	{
		setprometUlazaVrednost(getContext(), prometulazavrednost);
	}

	/**
	 * Set value of prometUlazaVrednost
	 * @param context
	 * @param prometulazavrednost
	 */
	public final void setprometUlazaVrednost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal prometulazavrednost)
	{
		getMendixObject().setValue(context, MemberNames.prometUlazaVrednost.toString(), prometulazavrednost);
	}

	/**
	 * @return value of prometIzlazaVrednost
	 */
	public final java.math.BigDecimal getprometIzlazaVrednost()
	{
		return getprometIzlazaVrednost(getContext());
	}

	/**
	 * @param context
	 * @return value of prometIzlazaVrednost
	 */
	public final java.math.BigDecimal getprometIzlazaVrednost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.prometIzlazaVrednost.toString());
	}

	/**
	 * Set value of prometIzlazaVrednost
	 * @param prometizlazavrednost
	 */
	public final void setprometIzlazaVrednost(java.math.BigDecimal prometizlazavrednost)
	{
		setprometIzlazaVrednost(getContext(), prometizlazavrednost);
	}

	/**
	 * Set value of prometIzlazaVrednost
	 * @param context
	 * @param prometizlazavrednost
	 */
	public final void setprometIzlazaVrednost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal prometizlazavrednost)
	{
		getMendixObject().setValue(context, MemberNames.prometIzlazaVrednost.toString(), prometizlazavrednost);
	}

	/**
	 * @return value of ukupnaVrednost
	 */
	public final java.math.BigDecimal getukupnaVrednost()
	{
		return getukupnaVrednost(getContext());
	}

	/**
	 * @param context
	 * @return value of ukupnaVrednost
	 */
	public final java.math.BigDecimal getukupnaVrednost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ukupnaVrednost.toString());
	}

	/**
	 * Set value of ukupnaVrednost
	 * @param ukupnavrednost
	 */
	public final void setukupnaVrednost(java.math.BigDecimal ukupnavrednost)
	{
		setukupnaVrednost(getContext(), ukupnavrednost);
	}

	/**
	 * Set value of ukupnaVrednost
	 * @param context
	 * @param ukupnavrednost
	 */
	public final void setukupnaVrednost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ukupnavrednost)
	{
		getMendixObject().setValue(context, MemberNames.ukupnaVrednost.toString(), ukupnavrednost);
	}

	/**
	 * @return value of cena
	 */
	public final java.math.BigDecimal getcena()
	{
		return getcena(getContext());
	}

	/**
	 * @param context
	 * @return value of cena
	 */
	public final java.math.BigDecimal getcena(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.cena.toString());
	}

	/**
	 * Set value of cena
	 * @param cena
	 */
	public final void setcena(java.math.BigDecimal cena)
	{
		setcena(getContext(), cena);
	}

	/**
	 * Set value of cena
	 * @param context
	 * @param cena
	 */
	public final void setcena(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal cena)
	{
		getMendixObject().setValue(context, MemberNames.cena.toString(), cena);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RobnaKartica_Magacin
	 */
	public final myfirstmodule.proxies.Magacin getRobnaKartica_Magacin() throws com.mendix.core.CoreException
	{
		return getRobnaKartica_Magacin(getContext());
	}

	/**
	 * @param context
	 * @return value of RobnaKartica_Magacin
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Magacin getRobnaKartica_Magacin(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Magacin result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RobnaKartica_Magacin.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Magacin.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RobnaKartica_Magacin
	 * @param robnakartica_magacin
	 */
	public final void setRobnaKartica_Magacin(myfirstmodule.proxies.Magacin robnakartica_magacin)
	{
		setRobnaKartica_Magacin(getContext(), robnakartica_magacin);
	}

	/**
	 * Set value of RobnaKartica_Magacin
	 * @param context
	 * @param robnakartica_magacin
	 */
	public final void setRobnaKartica_Magacin(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Magacin robnakartica_magacin)
	{
		if (robnakartica_magacin == null) {
			getMendixObject().setValue(context, MemberNames.RobnaKartica_Magacin.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RobnaKartica_Magacin.toString(), robnakartica_magacin.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RobnaKartica_RobaIliUsluga
	 */
	public final myfirstmodule.proxies.RobaIliUsluga getRobnaKartica_RobaIliUsluga() throws com.mendix.core.CoreException
	{
		return getRobnaKartica_RobaIliUsluga(getContext());
	}

	/**
	 * @param context
	 * @return value of RobnaKartica_RobaIliUsluga
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.RobaIliUsluga getRobnaKartica_RobaIliUsluga(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.RobaIliUsluga result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RobnaKartica_RobaIliUsluga.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.RobaIliUsluga.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RobnaKartica_RobaIliUsluga
	 * @param robnakartica_robailiusluga
	 */
	public final void setRobnaKartica_RobaIliUsluga(myfirstmodule.proxies.RobaIliUsluga robnakartica_robailiusluga)
	{
		setRobnaKartica_RobaIliUsluga(getContext(), robnakartica_robailiusluga);
	}

	/**
	 * Set value of RobnaKartica_RobaIliUsluga
	 * @param context
	 * @param robnakartica_robailiusluga
	 */
	public final void setRobnaKartica_RobaIliUsluga(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.RobaIliUsluga robnakartica_robailiusluga)
	{
		if (robnakartica_robailiusluga == null) {
			getMendixObject().setValue(context, MemberNames.RobnaKartica_RobaIliUsluga.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RobnaKartica_RobaIliUsluga.toString(), robnakartica_robailiusluga.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RobnaKartica_PoslovnaGodina
	 */
	public final myfirstmodule.proxies.PoslovnaGodina getRobnaKartica_PoslovnaGodina() throws com.mendix.core.CoreException
	{
		return getRobnaKartica_PoslovnaGodina(getContext());
	}

	/**
	 * @param context
	 * @return value of RobnaKartica_PoslovnaGodina
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.PoslovnaGodina getRobnaKartica_PoslovnaGodina(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.PoslovnaGodina result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RobnaKartica_PoslovnaGodina.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.PoslovnaGodina.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RobnaKartica_PoslovnaGodina
	 * @param robnakartica_poslovnagodina
	 */
	public final void setRobnaKartica_PoslovnaGodina(myfirstmodule.proxies.PoslovnaGodina robnakartica_poslovnagodina)
	{
		setRobnaKartica_PoslovnaGodina(getContext(), robnakartica_poslovnagodina);
	}

	/**
	 * Set value of RobnaKartica_PoslovnaGodina
	 * @param context
	 * @param robnakartica_poslovnagodina
	 */
	public final void setRobnaKartica_PoslovnaGodina(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.PoslovnaGodina robnakartica_poslovnagodina)
	{
		if (robnakartica_poslovnagodina == null) {
			getMendixObject().setValue(context, MemberNames.RobnaKartica_PoslovnaGodina.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RobnaKartica_PoslovnaGodina.toString(), robnakartica_poslovnagodina.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return robnaKarticaMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.RobnaKartica that = (myfirstmodule.proxies.RobnaKartica) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
