// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum SmerPrometa
{
	ulaz("613bdfa1-f8a6-492c-b05b-1e5ebf7f2ff0"),
	izlaz("d40ad1a7-ecb6-45d0-b85c-3a0a8083e85b");

	private final java.lang.String i18nCaptionKey;
	
	private SmerPrometa(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
