// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum StatusPopisa
{
	uFaziFormiranja("8f83024f-ad4a-46ff-9620-d916f52f4ca9"),
	proknjizen("f6c28af1-ff2a-4af6-9152-d4e0ab8d118a"),
	storniran("c5269622-f5a4-4a99-93b8-cf311ca93901"),
	otvorenoPocetnoStanje("214b0a11-7f36-49df-b97f-250b80d7633b");

	private final java.lang.String i18nCaptionKey;
	
	private StatusPopisa(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
