// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum StatusDokumenta
{
	uFaziFormiranja("6ed56ec6-6e83-44e7-8841-32658e1b76ca"),
	proknjizen("0d40484f-6651-4cac-b268-2726f251e49b");

	private final java.lang.String i18nCaptionKey;
	
	private StatusDokumenta(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
