// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class StavkePrometnogDokumenta implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject stavkePrometnogDokumentaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.StavkePrometnogDokumenta";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		kolicina("kolicina"),
		cena("cena"),
		vrednost("vrednost"),
		StavkePrometnogDokumenta_PrometniDokument("MyFirstModule.StavkePrometnogDokumenta_PrometniDokument"),
		StavkePrometnogDokumenta_RobaIliUsluga("MyFirstModule.StavkePrometnogDokumenta_RobaIliUsluga");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public StavkePrometnogDokumenta(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected StavkePrometnogDokumenta(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject stavkePrometnogDokumentaMendixObject)
	{
		if (stavkePrometnogDokumentaMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!stavkePrometnogDokumentaMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.stavkePrometnogDokumentaMendixObject = stavkePrometnogDokumentaMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.StavkePrometnogDokumenta initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.StavkePrometnogDokumenta(context, mendixObject);
	}

	public static myfirstmodule.proxies.StavkePrometnogDokumenta load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.StavkePrometnogDokumenta.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.StavkePrometnogDokumenta> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.StavkePrometnogDokumenta.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of kolicina
	 */
	public final java.lang.Integer getkolicina()
	{
		return getkolicina(getContext());
	}

	/**
	 * @param context
	 * @return value of kolicina
	 */
	public final java.lang.Integer getkolicina(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.kolicina.toString());
	}

	/**
	 * Set value of kolicina
	 * @param kolicina
	 */
	public final void setkolicina(java.lang.Integer kolicina)
	{
		setkolicina(getContext(), kolicina);
	}

	/**
	 * Set value of kolicina
	 * @param context
	 * @param kolicina
	 */
	public final void setkolicina(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer kolicina)
	{
		getMendixObject().setValue(context, MemberNames.kolicina.toString(), kolicina);
	}

	/**
	 * @return value of cena
	 */
	public final java.math.BigDecimal getcena()
	{
		return getcena(getContext());
	}

	/**
	 * @param context
	 * @return value of cena
	 */
	public final java.math.BigDecimal getcena(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.cena.toString());
	}

	/**
	 * Set value of cena
	 * @param cena
	 */
	public final void setcena(java.math.BigDecimal cena)
	{
		setcena(getContext(), cena);
	}

	/**
	 * Set value of cena
	 * @param context
	 * @param cena
	 */
	public final void setcena(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal cena)
	{
		getMendixObject().setValue(context, MemberNames.cena.toString(), cena);
	}

	/**
	 * @return value of vrednost
	 */
	public final java.lang.Integer getvrednost()
	{
		return getvrednost(getContext());
	}

	/**
	 * @param context
	 * @return value of vrednost
	 */
	public final java.lang.Integer getvrednost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.vrednost.toString());
	}

	/**
	 * Set value of vrednost
	 * @param vrednost
	 */
	public final void setvrednost(java.lang.Integer vrednost)
	{
		setvrednost(getContext(), vrednost);
	}

	/**
	 * Set value of vrednost
	 * @param context
	 * @param vrednost
	 */
	public final void setvrednost(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer vrednost)
	{
		getMendixObject().setValue(context, MemberNames.vrednost.toString(), vrednost);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of StavkePrometnogDokumenta_PrometniDokument
	 */
	public final myfirstmodule.proxies.PrometniDokument getStavkePrometnogDokumenta_PrometniDokument() throws com.mendix.core.CoreException
	{
		return getStavkePrometnogDokumenta_PrometniDokument(getContext());
	}

	/**
	 * @param context
	 * @return value of StavkePrometnogDokumenta_PrometniDokument
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.PrometniDokument getStavkePrometnogDokumenta_PrometniDokument(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.PrometniDokument result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StavkePrometnogDokumenta_PrometniDokument.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.PrometniDokument.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of StavkePrometnogDokumenta_PrometniDokument
	 * @param stavkeprometnogdokumenta_prometnidokument
	 */
	public final void setStavkePrometnogDokumenta_PrometniDokument(myfirstmodule.proxies.PrometniDokument stavkeprometnogdokumenta_prometnidokument)
	{
		setStavkePrometnogDokumenta_PrometniDokument(getContext(), stavkeprometnogdokumenta_prometnidokument);
	}

	/**
	 * Set value of StavkePrometnogDokumenta_PrometniDokument
	 * @param context
	 * @param stavkeprometnogdokumenta_prometnidokument
	 */
	public final void setStavkePrometnogDokumenta_PrometniDokument(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.PrometniDokument stavkeprometnogdokumenta_prometnidokument)
	{
		if (stavkeprometnogdokumenta_prometnidokument == null) {
			getMendixObject().setValue(context, MemberNames.StavkePrometnogDokumenta_PrometniDokument.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.StavkePrometnogDokumenta_PrometniDokument.toString(), stavkeprometnogdokumenta_prometnidokument.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of StavkePrometnogDokumenta_RobaIliUsluga
	 */
	public final myfirstmodule.proxies.RobaIliUsluga getStavkePrometnogDokumenta_RobaIliUsluga() throws com.mendix.core.CoreException
	{
		return getStavkePrometnogDokumenta_RobaIliUsluga(getContext());
	}

	/**
	 * @param context
	 * @return value of StavkePrometnogDokumenta_RobaIliUsluga
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.RobaIliUsluga getStavkePrometnogDokumenta_RobaIliUsluga(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.RobaIliUsluga result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StavkePrometnogDokumenta_RobaIliUsluga.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.RobaIliUsluga.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of StavkePrometnogDokumenta_RobaIliUsluga
	 * @param stavkeprometnogdokumenta_robailiusluga
	 */
	public final void setStavkePrometnogDokumenta_RobaIliUsluga(myfirstmodule.proxies.RobaIliUsluga stavkeprometnogdokumenta_robailiusluga)
	{
		setStavkePrometnogDokumenta_RobaIliUsluga(getContext(), stavkeprometnogdokumenta_robailiusluga);
	}

	/**
	 * Set value of StavkePrometnogDokumenta_RobaIliUsluga
	 * @param context
	 * @param stavkeprometnogdokumenta_robailiusluga
	 */
	public final void setStavkePrometnogDokumenta_RobaIliUsluga(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.RobaIliUsluga stavkeprometnogdokumenta_robailiusluga)
	{
		if (stavkeprometnogdokumenta_robailiusluga == null) {
			getMendixObject().setValue(context, MemberNames.StavkePrometnogDokumenta_RobaIliUsluga.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.StavkePrometnogDokumenta_RobaIliUsluga.toString(), stavkeprometnogdokumenta_robailiusluga.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return stavkePrometnogDokumentaMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.StavkePrometnogDokumenta that = (myfirstmodule.proxies.StavkePrometnogDokumenta) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
