// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class StavkaPopisnogDokumenta implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject stavkaPopisnogDokumentaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.StavkaPopisnogDokumenta";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		kolicinaPoPopisu("kolicinaPoPopisu"),
		StavkaPopisnogDokumenta_PopisniDokument("MyFirstModule.StavkaPopisnogDokumenta_PopisniDokument"),
		StavkaPopisnogDokumenta_RobaIliUsluga("MyFirstModule.StavkaPopisnogDokumenta_RobaIliUsluga");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public StavkaPopisnogDokumenta(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected StavkaPopisnogDokumenta(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject stavkaPopisnogDokumentaMendixObject)
	{
		if (stavkaPopisnogDokumentaMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!stavkaPopisnogDokumentaMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.stavkaPopisnogDokumentaMendixObject = stavkaPopisnogDokumentaMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.StavkaPopisnogDokumenta initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.StavkaPopisnogDokumenta(context, mendixObject);
	}

	public static myfirstmodule.proxies.StavkaPopisnogDokumenta load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.StavkaPopisnogDokumenta.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.StavkaPopisnogDokumenta> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.StavkaPopisnogDokumenta.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of kolicinaPoPopisu
	 */
	public final java.lang.Integer getkolicinaPoPopisu()
	{
		return getkolicinaPoPopisu(getContext());
	}

	/**
	 * @param context
	 * @return value of kolicinaPoPopisu
	 */
	public final java.lang.Integer getkolicinaPoPopisu(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.kolicinaPoPopisu.toString());
	}

	/**
	 * Set value of kolicinaPoPopisu
	 * @param kolicinapopopisu
	 */
	public final void setkolicinaPoPopisu(java.lang.Integer kolicinapopopisu)
	{
		setkolicinaPoPopisu(getContext(), kolicinapopopisu);
	}

	/**
	 * Set value of kolicinaPoPopisu
	 * @param context
	 * @param kolicinapopopisu
	 */
	public final void setkolicinaPoPopisu(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer kolicinapopopisu)
	{
		getMendixObject().setValue(context, MemberNames.kolicinaPoPopisu.toString(), kolicinapopopisu);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of StavkaPopisnogDokumenta_PopisniDokument
	 */
	public final myfirstmodule.proxies.PopisniDokument getStavkaPopisnogDokumenta_PopisniDokument() throws com.mendix.core.CoreException
	{
		return getStavkaPopisnogDokumenta_PopisniDokument(getContext());
	}

	/**
	 * @param context
	 * @return value of StavkaPopisnogDokumenta_PopisniDokument
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.PopisniDokument getStavkaPopisnogDokumenta_PopisniDokument(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.PopisniDokument result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StavkaPopisnogDokumenta_PopisniDokument.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.PopisniDokument.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of StavkaPopisnogDokumenta_PopisniDokument
	 * @param stavkapopisnogdokumenta_popisnidokument
	 */
	public final void setStavkaPopisnogDokumenta_PopisniDokument(myfirstmodule.proxies.PopisniDokument stavkapopisnogdokumenta_popisnidokument)
	{
		setStavkaPopisnogDokumenta_PopisniDokument(getContext(), stavkapopisnogdokumenta_popisnidokument);
	}

	/**
	 * Set value of StavkaPopisnogDokumenta_PopisniDokument
	 * @param context
	 * @param stavkapopisnogdokumenta_popisnidokument
	 */
	public final void setStavkaPopisnogDokumenta_PopisniDokument(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.PopisniDokument stavkapopisnogdokumenta_popisnidokument)
	{
		if (stavkapopisnogdokumenta_popisnidokument == null) {
			getMendixObject().setValue(context, MemberNames.StavkaPopisnogDokumenta_PopisniDokument.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.StavkaPopisnogDokumenta_PopisniDokument.toString(), stavkapopisnogdokumenta_popisnidokument.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of StavkaPopisnogDokumenta_RobaIliUsluga
	 */
	public final myfirstmodule.proxies.RobaIliUsluga getStavkaPopisnogDokumenta_RobaIliUsluga() throws com.mendix.core.CoreException
	{
		return getStavkaPopisnogDokumenta_RobaIliUsluga(getContext());
	}

	/**
	 * @param context
	 * @return value of StavkaPopisnogDokumenta_RobaIliUsluga
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.RobaIliUsluga getStavkaPopisnogDokumenta_RobaIliUsluga(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.RobaIliUsluga result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StavkaPopisnogDokumenta_RobaIliUsluga.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.RobaIliUsluga.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of StavkaPopisnogDokumenta_RobaIliUsluga
	 * @param stavkapopisnogdokumenta_robailiusluga
	 */
	public final void setStavkaPopisnogDokumenta_RobaIliUsluga(myfirstmodule.proxies.RobaIliUsluga stavkapopisnogdokumenta_robailiusluga)
	{
		setStavkaPopisnogDokumenta_RobaIliUsluga(getContext(), stavkapopisnogdokumenta_robailiusluga);
	}

	/**
	 * Set value of StavkaPopisnogDokumenta_RobaIliUsluga
	 * @param context
	 * @param stavkapopisnogdokumenta_robailiusluga
	 */
	public final void setStavkaPopisnogDokumenta_RobaIliUsluga(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.RobaIliUsluga stavkapopisnogdokumenta_robailiusluga)
	{
		if (stavkapopisnogdokumenta_robailiusluga == null) {
			getMendixObject().setValue(context, MemberNames.StavkaPopisnogDokumenta_RobaIliUsluga.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.StavkaPopisnogDokumenta_RobaIliUsluga.toString(), stavkapopisnogdokumenta_robailiusluga.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return stavkaPopisnogDokumentaMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.StavkaPopisnogDokumenta that = (myfirstmodule.proxies.StavkaPopisnogDokumenta) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
