// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum VrstaPartnera
{
	prodavac("596ff220-c02b-49fb-9303-e40d25e1f8dd"),
	dobavljac("904e54c1-c67f-4013-b3e5-4eecf1ed44b7");

	private final java.lang.String i18nCaptionKey;
	
	private VrstaPartnera(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
