// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum VrstaPrometnogDokumenta
{
	otpremnica("95d70936-bf28-459d-b57b-02b882a3dea5"),
	medjumagacinskiPromet("2a339df9-3ab7-44b1-b240-03fe18b0d25c");

	private final java.lang.String i18nCaptionKey;
	
	private VrstaPrometnogDokumenta(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
