// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum VrstaPrometa
{
	primka("6f6940c8-b970-489c-952f-4bae97fd8b84"),
	otpremnica("7f0cdfed-dd5f-44b0-882d-67dcac8e08b2"),
	medjumagacinskiPromet("3b017e33-0da8-4af7-b9c0-041b6803bf73"),
	korekcijaPoPopisu("1ec768b6-f33a-43d6-a885-6441f2ce4a02"),
	pocetnoStanje("4f08691a-1ca3-4db4-a07f-49949104fa52"),
	nivelacija("3685bd92-fc34-4f4c-8c69-defd91f8d154");

	private final java.lang.String i18nCaptionKey;
	
	private VrstaPrometa(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
