// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package prodaja.proxies;

public class Cena implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cenaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Prodaja.Cena";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		iznos("iznos"),
		Cena_Cenovnik("Prodaja.Cena_Cenovnik"),
		Cena_RobaIliUsluga("Prodaja.Cena_RobaIliUsluga");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Cena(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Cena(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cenaMendixObject)
	{
		if (cenaMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!cenaMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.cenaMendixObject = cenaMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static prodaja.proxies.Cena initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new prodaja.proxies.Cena(context, mendixObject);
	}

	public static prodaja.proxies.Cena load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return prodaja.proxies.Cena.initialize(context, mendixObject);
	}

	public static java.util.List<prodaja.proxies.Cena> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> prodaja.proxies.Cena.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of iznos
	 */
	public final java.math.BigDecimal getiznos()
	{
		return getiznos(getContext());
	}

	/**
	 * @param context
	 * @return value of iznos
	 */
	public final java.math.BigDecimal getiznos(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.iznos.toString());
	}

	/**
	 * Set value of iznos
	 * @param iznos
	 */
	public final void setiznos(java.math.BigDecimal iznos)
	{
		setiznos(getContext(), iznos);
	}

	/**
	 * Set value of iznos
	 * @param context
	 * @param iznos
	 */
	public final void setiznos(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal iznos)
	{
		getMendixObject().setValue(context, MemberNames.iznos.toString(), iznos);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Cena_Cenovnik
	 */
	public final prodaja.proxies.Cenovnik getCena_Cenovnik() throws com.mendix.core.CoreException
	{
		return getCena_Cenovnik(getContext());
	}

	/**
	 * @param context
	 * @return value of Cena_Cenovnik
	 * @throws com.mendix.core.CoreException
	 */
	public final prodaja.proxies.Cenovnik getCena_Cenovnik(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		prodaja.proxies.Cenovnik result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Cena_Cenovnik.toString());
		if (identifier != null) {
			result = prodaja.proxies.Cenovnik.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Cena_Cenovnik
	 * @param cena_cenovnik
	 */
	public final void setCena_Cenovnik(prodaja.proxies.Cenovnik cena_cenovnik)
	{
		setCena_Cenovnik(getContext(), cena_cenovnik);
	}

	/**
	 * Set value of Cena_Cenovnik
	 * @param context
	 * @param cena_cenovnik
	 */
	public final void setCena_Cenovnik(com.mendix.systemwideinterfaces.core.IContext context, prodaja.proxies.Cenovnik cena_cenovnik)
	{
		if (cena_cenovnik == null) {
			getMendixObject().setValue(context, MemberNames.Cena_Cenovnik.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Cena_Cenovnik.toString(), cena_cenovnik.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Cena_RobaIliUsluga
	 */
	public final myfirstmodule.proxies.RobaIliUsluga getCena_RobaIliUsluga() throws com.mendix.core.CoreException
	{
		return getCena_RobaIliUsluga(getContext());
	}

	/**
	 * @param context
	 * @return value of Cena_RobaIliUsluga
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.RobaIliUsluga getCena_RobaIliUsluga(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.RobaIliUsluga result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Cena_RobaIliUsluga.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.RobaIliUsluga.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Cena_RobaIliUsluga
	 * @param cena_robailiusluga
	 */
	public final void setCena_RobaIliUsluga(myfirstmodule.proxies.RobaIliUsluga cena_robailiusluga)
	{
		setCena_RobaIliUsluga(getContext(), cena_robailiusluga);
	}

	/**
	 * Set value of Cena_RobaIliUsluga
	 * @param context
	 * @param cena_robailiusluga
	 */
	public final void setCena_RobaIliUsluga(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.RobaIliUsluga cena_robailiusluga)
	{
		if (cena_robailiusluga == null) {
			getMendixObject().setValue(context, MemberNames.Cena_RobaIliUsluga.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Cena_RobaIliUsluga.toString(), cena_robailiusluga.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cenaMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final prodaja.proxies.Cena that = (prodaja.proxies.Cena) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
