// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package prodaja.proxies;

public class Cenovnik implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cenovnikMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Prodaja.Cenovnik";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		datumVazenja("datumVazenja"),
		Cenovnik_Preduzece("Prodaja.Cenovnik_Preduzece");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Cenovnik(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Cenovnik(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cenovnikMendixObject)
	{
		if (cenovnikMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!cenovnikMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.cenovnikMendixObject = cenovnikMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static prodaja.proxies.Cenovnik initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new prodaja.proxies.Cenovnik(context, mendixObject);
	}

	public static prodaja.proxies.Cenovnik load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return prodaja.proxies.Cenovnik.initialize(context, mendixObject);
	}

	public static java.util.List<prodaja.proxies.Cenovnik> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> prodaja.proxies.Cenovnik.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of datumVazenja
	 */
	public final java.util.Date getdatumVazenja()
	{
		return getdatumVazenja(getContext());
	}

	/**
	 * @param context
	 * @return value of datumVazenja
	 */
	public final java.util.Date getdatumVazenja(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.datumVazenja.toString());
	}

	/**
	 * Set value of datumVazenja
	 * @param datumvazenja
	 */
	public final void setdatumVazenja(java.util.Date datumvazenja)
	{
		setdatumVazenja(getContext(), datumvazenja);
	}

	/**
	 * Set value of datumVazenja
	 * @param context
	 * @param datumvazenja
	 */
	public final void setdatumVazenja(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datumvazenja)
	{
		getMendixObject().setValue(context, MemberNames.datumVazenja.toString(), datumvazenja);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Cenovnik_Preduzece
	 */
	public final myfirstmodule.proxies.Preduzece getCenovnik_Preduzece() throws com.mendix.core.CoreException
	{
		return getCenovnik_Preduzece(getContext());
	}

	/**
	 * @param context
	 * @return value of Cenovnik_Preduzece
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Preduzece getCenovnik_Preduzece(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Preduzece result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Cenovnik_Preduzece.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Preduzece.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Cenovnik_Preduzece
	 * @param cenovnik_preduzece
	 */
	public final void setCenovnik_Preduzece(myfirstmodule.proxies.Preduzece cenovnik_preduzece)
	{
		setCenovnik_Preduzece(getContext(), cenovnik_preduzece);
	}

	/**
	 * Set value of Cenovnik_Preduzece
	 * @param context
	 * @param cenovnik_preduzece
	 */
	public final void setCenovnik_Preduzece(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Preduzece cenovnik_preduzece)
	{
		if (cenovnik_preduzece == null) {
			getMendixObject().setValue(context, MemberNames.Cenovnik_Preduzece.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Cenovnik_Preduzece.toString(), cenovnik_preduzece.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cenovnikMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final prodaja.proxies.Cenovnik that = (prodaja.proxies.Cenovnik) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
