// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package prodaja.proxies;

public class IzlaznaFaktura implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject izlaznaFakturaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Prodaja.IzlaznaFaktura";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		datumFakture("datumFakture"),
		IzlaznaFaktura_PoslovniPartner("Prodaja.IzlaznaFaktura_PoslovniPartner"),
		IzlaznaFaktura_PoslovnaGodina("Prodaja.IzlaznaFaktura_PoslovnaGodina");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public IzlaznaFaktura(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected IzlaznaFaktura(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject izlaznaFakturaMendixObject)
	{
		if (izlaznaFakturaMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!izlaznaFakturaMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.izlaznaFakturaMendixObject = izlaznaFakturaMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static prodaja.proxies.IzlaznaFaktura initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new prodaja.proxies.IzlaznaFaktura(context, mendixObject);
	}

	public static prodaja.proxies.IzlaznaFaktura load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return prodaja.proxies.IzlaznaFaktura.initialize(context, mendixObject);
	}

	public static java.util.List<prodaja.proxies.IzlaznaFaktura> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> prodaja.proxies.IzlaznaFaktura.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of datumFakture
	 */
	public final java.util.Date getdatumFakture()
	{
		return getdatumFakture(getContext());
	}

	/**
	 * @param context
	 * @return value of datumFakture
	 */
	public final java.util.Date getdatumFakture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.datumFakture.toString());
	}

	/**
	 * Set value of datumFakture
	 * @param datumfakture
	 */
	public final void setdatumFakture(java.util.Date datumfakture)
	{
		setdatumFakture(getContext(), datumfakture);
	}

	/**
	 * Set value of datumFakture
	 * @param context
	 * @param datumfakture
	 */
	public final void setdatumFakture(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datumfakture)
	{
		getMendixObject().setValue(context, MemberNames.datumFakture.toString(), datumfakture);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of IzlaznaFaktura_PoslovniPartner
	 */
	public final myfirstmodule.proxies.PoslovniPartner getIzlaznaFaktura_PoslovniPartner() throws com.mendix.core.CoreException
	{
		return getIzlaznaFaktura_PoslovniPartner(getContext());
	}

	/**
	 * @param context
	 * @return value of IzlaznaFaktura_PoslovniPartner
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.PoslovniPartner getIzlaznaFaktura_PoslovniPartner(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.PoslovniPartner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.IzlaznaFaktura_PoslovniPartner.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.PoslovniPartner.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of IzlaznaFaktura_PoslovniPartner
	 * @param izlaznafaktura_poslovnipartner
	 */
	public final void setIzlaznaFaktura_PoslovniPartner(myfirstmodule.proxies.PoslovniPartner izlaznafaktura_poslovnipartner)
	{
		setIzlaznaFaktura_PoslovniPartner(getContext(), izlaznafaktura_poslovnipartner);
	}

	/**
	 * Set value of IzlaznaFaktura_PoslovniPartner
	 * @param context
	 * @param izlaznafaktura_poslovnipartner
	 */
	public final void setIzlaznaFaktura_PoslovniPartner(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.PoslovniPartner izlaznafaktura_poslovnipartner)
	{
		if (izlaznafaktura_poslovnipartner == null) {
			getMendixObject().setValue(context, MemberNames.IzlaznaFaktura_PoslovniPartner.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.IzlaznaFaktura_PoslovniPartner.toString(), izlaznafaktura_poslovnipartner.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of IzlaznaFaktura_PoslovnaGodina
	 */
	public final myfirstmodule.proxies.PoslovnaGodina getIzlaznaFaktura_PoslovnaGodina() throws com.mendix.core.CoreException
	{
		return getIzlaznaFaktura_PoslovnaGodina(getContext());
	}

	/**
	 * @param context
	 * @return value of IzlaznaFaktura_PoslovnaGodina
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.PoslovnaGodina getIzlaznaFaktura_PoslovnaGodina(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.PoslovnaGodina result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.IzlaznaFaktura_PoslovnaGodina.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.PoslovnaGodina.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of IzlaznaFaktura_PoslovnaGodina
	 * @param izlaznafaktura_poslovnagodina
	 */
	public final void setIzlaznaFaktura_PoslovnaGodina(myfirstmodule.proxies.PoslovnaGodina izlaznafaktura_poslovnagodina)
	{
		setIzlaznaFaktura_PoslovnaGodina(getContext(), izlaznafaktura_poslovnagodina);
	}

	/**
	 * Set value of IzlaznaFaktura_PoslovnaGodina
	 * @param context
	 * @param izlaznafaktura_poslovnagodina
	 */
	public final void setIzlaznaFaktura_PoslovnaGodina(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.PoslovnaGodina izlaznafaktura_poslovnagodina)
	{
		if (izlaznafaktura_poslovnagodina == null) {
			getMendixObject().setValue(context, MemberNames.IzlaznaFaktura_PoslovnaGodina.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.IzlaznaFaktura_PoslovnaGodina.toString(), izlaznafaktura_poslovnagodina.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return izlaznaFakturaMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final prodaja.proxies.IzlaznaFaktura that = (prodaja.proxies.IzlaznaFaktura) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
