// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package prodaja.proxies;

public class IznosPDV implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject iznosPDVMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Prodaja.IznosPDV";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		iznos("iznos"),
		stopaPDV("stopaPDV"),
		vaziOd("vaziOd"),
		IznosPDV_Preduzece("Prodaja.IznosPDV_Preduzece");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public IznosPDV(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected IznosPDV(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject iznosPDVMendixObject)
	{
		if (iznosPDVMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!iznosPDVMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.iznosPDVMendixObject = iznosPDVMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static prodaja.proxies.IznosPDV initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new prodaja.proxies.IznosPDV(context, mendixObject);
	}

	public static prodaja.proxies.IznosPDV load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return prodaja.proxies.IznosPDV.initialize(context, mendixObject);
	}

	public static java.util.List<prodaja.proxies.IznosPDV> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> prodaja.proxies.IznosPDV.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of iznos
	 */
	public final java.math.BigDecimal getiznos()
	{
		return getiznos(getContext());
	}

	/**
	 * @param context
	 * @return value of iznos
	 */
	public final java.math.BigDecimal getiznos(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.iznos.toString());
	}

	/**
	 * Set value of iznos
	 * @param iznos
	 */
	public final void setiznos(java.math.BigDecimal iznos)
	{
		setiznos(getContext(), iznos);
	}

	/**
	 * Set value of iznos
	 * @param context
	 * @param iznos
	 */
	public final void setiznos(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal iznos)
	{
		getMendixObject().setValue(context, MemberNames.iznos.toString(), iznos);
	}

	/**
	 * Get value of stopaPDV
	 * @param stopapdv
	 */
	public final prodaja.proxies.StopaPDV getstopaPDV()
	{
		return getstopaPDV(getContext());
	}

	/**
	 * @param context
	 * @return value of stopaPDV
	 */
	public final prodaja.proxies.StopaPDV getstopaPDV(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.stopaPDV.toString());
		if (obj == null) {
			return null;
		}
		return prodaja.proxies.StopaPDV.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of stopaPDV
	 * @param stopapdv
	 */
	public final void setstopaPDV(prodaja.proxies.StopaPDV stopapdv)
	{
		setstopaPDV(getContext(), stopapdv);
	}

	/**
	 * Set value of stopaPDV
	 * @param context
	 * @param stopapdv
	 */
	public final void setstopaPDV(com.mendix.systemwideinterfaces.core.IContext context, prodaja.proxies.StopaPDV stopapdv)
	{
		if (stopapdv != null) {
			getMendixObject().setValue(context, MemberNames.stopaPDV.toString(), stopapdv.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.stopaPDV.toString(), null);
		}
	}

	/**
	 * @return value of vaziOd
	 */
	public final java.util.Date getvaziOd()
	{
		return getvaziOd(getContext());
	}

	/**
	 * @param context
	 * @return value of vaziOd
	 */
	public final java.util.Date getvaziOd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.vaziOd.toString());
	}

	/**
	 * Set value of vaziOd
	 * @param vaziod
	 */
	public final void setvaziOd(java.util.Date vaziod)
	{
		setvaziOd(getContext(), vaziod);
	}

	/**
	 * Set value of vaziOd
	 * @param context
	 * @param vaziod
	 */
	public final void setvaziOd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date vaziod)
	{
		getMendixObject().setValue(context, MemberNames.vaziOd.toString(), vaziod);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of IznosPDV_Preduzece
	 */
	public final myfirstmodule.proxies.Preduzece getIznosPDV_Preduzece() throws com.mendix.core.CoreException
	{
		return getIznosPDV_Preduzece(getContext());
	}

	/**
	 * @param context
	 * @return value of IznosPDV_Preduzece
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Preduzece getIznosPDV_Preduzece(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Preduzece result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.IznosPDV_Preduzece.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Preduzece.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of IznosPDV_Preduzece
	 * @param iznospdv_preduzece
	 */
	public final void setIznosPDV_Preduzece(myfirstmodule.proxies.Preduzece iznospdv_preduzece)
	{
		setIznosPDV_Preduzece(getContext(), iznospdv_preduzece);
	}

	/**
	 * Set value of IznosPDV_Preduzece
	 * @param context
	 * @param iznospdv_preduzece
	 */
	public final void setIznosPDV_Preduzece(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Preduzece iznospdv_preduzece)
	{
		if (iznospdv_preduzece == null) {
			getMendixObject().setValue(context, MemberNames.IznosPDV_Preduzece.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.IznosPDV_Preduzece.toString(), iznospdv_preduzece.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return iznosPDVMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final prodaja.proxies.IznosPDV that = (prodaja.proxies.IznosPDV) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
