// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package prodaja.proxies;

public class KategorijaRobe implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject kategorijaRobeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Prodaja.KategorijaRobe";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		nazivKategorije("nazivKategorije"),
		stopaPDV("stopaPDV"),
		KategorijaRobe_Preduzece("Prodaja.KategorijaRobe_Preduzece");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public KategorijaRobe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected KategorijaRobe(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject kategorijaRobeMendixObject)
	{
		if (kategorijaRobeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!kategorijaRobeMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.kategorijaRobeMendixObject = kategorijaRobeMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static prodaja.proxies.KategorijaRobe initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new prodaja.proxies.KategorijaRobe(context, mendixObject);
	}

	public static prodaja.proxies.KategorijaRobe load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return prodaja.proxies.KategorijaRobe.initialize(context, mendixObject);
	}

	public static java.util.List<prodaja.proxies.KategorijaRobe> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> prodaja.proxies.KategorijaRobe.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of nazivKategorije
	 */
	public final java.lang.String getnazivKategorije()
	{
		return getnazivKategorije(getContext());
	}

	/**
	 * @param context
	 * @return value of nazivKategorije
	 */
	public final java.lang.String getnazivKategorije(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.nazivKategorije.toString());
	}

	/**
	 * Set value of nazivKategorije
	 * @param nazivkategorije
	 */
	public final void setnazivKategorije(java.lang.String nazivkategorije)
	{
		setnazivKategorije(getContext(), nazivkategorije);
	}

	/**
	 * Set value of nazivKategorije
	 * @param context
	 * @param nazivkategorije
	 */
	public final void setnazivKategorije(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nazivkategorije)
	{
		getMendixObject().setValue(context, MemberNames.nazivKategorije.toString(), nazivkategorije);
	}

	/**
	 * Get value of stopaPDV
	 * @param stopapdv
	 */
	public final prodaja.proxies.StopaPDV getstopaPDV()
	{
		return getstopaPDV(getContext());
	}

	/**
	 * @param context
	 * @return value of stopaPDV
	 */
	public final prodaja.proxies.StopaPDV getstopaPDV(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.stopaPDV.toString());
		if (obj == null) {
			return null;
		}
		return prodaja.proxies.StopaPDV.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of stopaPDV
	 * @param stopapdv
	 */
	public final void setstopaPDV(prodaja.proxies.StopaPDV stopapdv)
	{
		setstopaPDV(getContext(), stopapdv);
	}

	/**
	 * Set value of stopaPDV
	 * @param context
	 * @param stopapdv
	 */
	public final void setstopaPDV(com.mendix.systemwideinterfaces.core.IContext context, prodaja.proxies.StopaPDV stopapdv)
	{
		if (stopapdv != null) {
			getMendixObject().setValue(context, MemberNames.stopaPDV.toString(), stopapdv.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.stopaPDV.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of KategorijaRobe_Preduzece
	 */
	public final myfirstmodule.proxies.Preduzece getKategorijaRobe_Preduzece() throws com.mendix.core.CoreException
	{
		return getKategorijaRobe_Preduzece(getContext());
	}

	/**
	 * @param context
	 * @return value of KategorijaRobe_Preduzece
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Preduzece getKategorijaRobe_Preduzece(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Preduzece result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.KategorijaRobe_Preduzece.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Preduzece.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of KategorijaRobe_Preduzece
	 * @param kategorijarobe_preduzece
	 */
	public final void setKategorijaRobe_Preduzece(myfirstmodule.proxies.Preduzece kategorijarobe_preduzece)
	{
		setKategorijaRobe_Preduzece(getContext(), kategorijarobe_preduzece);
	}

	/**
	 * Set value of KategorijaRobe_Preduzece
	 * @param context
	 * @param kategorijarobe_preduzece
	 */
	public final void setKategorijaRobe_Preduzece(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Preduzece kategorijarobe_preduzece)
	{
		if (kategorijarobe_preduzece == null) {
			getMendixObject().setValue(context, MemberNames.KategorijaRobe_Preduzece.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.KategorijaRobe_Preduzece.toString(), kategorijarobe_preduzece.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return kategorijaRobeMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final prodaja.proxies.KategorijaRobe that = (prodaja.proxies.KategorijaRobe) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
