// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package prodaja.proxies;

public class NarudzbenicaKupca implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject narudzbenicaKupcaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Prodaja.NarudzbenicaKupca";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		rokIsporuke("rokIsporuke"),
		nacinPakovanja("nacinPakovanja"),
		nacinPlacanja("nacinPlacanja"),
		mestoPreuzimanjaIsporuke("mestoPreuzimanjaIsporuke"),
		NarudzbenicaKupca_IzlaznaFaktura("Prodaja.NarudzbenicaKupca_IzlaznaFaktura"),
		NarudzbenicaKupca_PoslovniPartner("Prodaja.NarudzbenicaKupca_PoslovniPartner"),
		NarudzbenicaKupca_PoslovnaGodina("Prodaja.NarudzbenicaKupca_PoslovnaGodina"),
		NarudzbenicaKupca_Preduzece("Prodaja.NarudzbenicaKupca_Preduzece");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public NarudzbenicaKupca(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected NarudzbenicaKupca(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject narudzbenicaKupcaMendixObject)
	{
		if (narudzbenicaKupcaMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!narudzbenicaKupcaMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.narudzbenicaKupcaMendixObject = narudzbenicaKupcaMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static prodaja.proxies.NarudzbenicaKupca initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new prodaja.proxies.NarudzbenicaKupca(context, mendixObject);
	}

	public static prodaja.proxies.NarudzbenicaKupca load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return prodaja.proxies.NarudzbenicaKupca.initialize(context, mendixObject);
	}

	public static java.util.List<prodaja.proxies.NarudzbenicaKupca> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> prodaja.proxies.NarudzbenicaKupca.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of rokIsporuke
	 */
	public final java.util.Date getrokIsporuke()
	{
		return getrokIsporuke(getContext());
	}

	/**
	 * @param context
	 * @return value of rokIsporuke
	 */
	public final java.util.Date getrokIsporuke(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.rokIsporuke.toString());
	}

	/**
	 * Set value of rokIsporuke
	 * @param rokisporuke
	 */
	public final void setrokIsporuke(java.util.Date rokisporuke)
	{
		setrokIsporuke(getContext(), rokisporuke);
	}

	/**
	 * Set value of rokIsporuke
	 * @param context
	 * @param rokisporuke
	 */
	public final void setrokIsporuke(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date rokisporuke)
	{
		getMendixObject().setValue(context, MemberNames.rokIsporuke.toString(), rokisporuke);
	}

	/**
	 * @return value of nacinPakovanja
	 */
	public final java.lang.String getnacinPakovanja()
	{
		return getnacinPakovanja(getContext());
	}

	/**
	 * @param context
	 * @return value of nacinPakovanja
	 */
	public final java.lang.String getnacinPakovanja(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.nacinPakovanja.toString());
	}

	/**
	 * Set value of nacinPakovanja
	 * @param nacinpakovanja
	 */
	public final void setnacinPakovanja(java.lang.String nacinpakovanja)
	{
		setnacinPakovanja(getContext(), nacinpakovanja);
	}

	/**
	 * Set value of nacinPakovanja
	 * @param context
	 * @param nacinpakovanja
	 */
	public final void setnacinPakovanja(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nacinpakovanja)
	{
		getMendixObject().setValue(context, MemberNames.nacinPakovanja.toString(), nacinpakovanja);
	}

	/**
	 * @return value of nacinPlacanja
	 */
	public final java.lang.String getnacinPlacanja()
	{
		return getnacinPlacanja(getContext());
	}

	/**
	 * @param context
	 * @return value of nacinPlacanja
	 */
	public final java.lang.String getnacinPlacanja(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.nacinPlacanja.toString());
	}

	/**
	 * Set value of nacinPlacanja
	 * @param nacinplacanja
	 */
	public final void setnacinPlacanja(java.lang.String nacinplacanja)
	{
		setnacinPlacanja(getContext(), nacinplacanja);
	}

	/**
	 * Set value of nacinPlacanja
	 * @param context
	 * @param nacinplacanja
	 */
	public final void setnacinPlacanja(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nacinplacanja)
	{
		getMendixObject().setValue(context, MemberNames.nacinPlacanja.toString(), nacinplacanja);
	}

	/**
	 * @return value of mestoPreuzimanjaIsporuke
	 */
	public final java.lang.String getmestoPreuzimanjaIsporuke()
	{
		return getmestoPreuzimanjaIsporuke(getContext());
	}

	/**
	 * @param context
	 * @return value of mestoPreuzimanjaIsporuke
	 */
	public final java.lang.String getmestoPreuzimanjaIsporuke(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.mestoPreuzimanjaIsporuke.toString());
	}

	/**
	 * Set value of mestoPreuzimanjaIsporuke
	 * @param mestopreuzimanjaisporuke
	 */
	public final void setmestoPreuzimanjaIsporuke(java.lang.String mestopreuzimanjaisporuke)
	{
		setmestoPreuzimanjaIsporuke(getContext(), mestopreuzimanjaisporuke);
	}

	/**
	 * Set value of mestoPreuzimanjaIsporuke
	 * @param context
	 * @param mestopreuzimanjaisporuke
	 */
	public final void setmestoPreuzimanjaIsporuke(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mestopreuzimanjaisporuke)
	{
		getMendixObject().setValue(context, MemberNames.mestoPreuzimanjaIsporuke.toString(), mestopreuzimanjaisporuke);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of NarudzbenicaKupca_IzlaznaFaktura
	 */
	public final prodaja.proxies.IzlaznaFaktura getNarudzbenicaKupca_IzlaznaFaktura() throws com.mendix.core.CoreException
	{
		return getNarudzbenicaKupca_IzlaznaFaktura(getContext());
	}

	/**
	 * @param context
	 * @return value of NarudzbenicaKupca_IzlaznaFaktura
	 * @throws com.mendix.core.CoreException
	 */
	public final prodaja.proxies.IzlaznaFaktura getNarudzbenicaKupca_IzlaznaFaktura(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		prodaja.proxies.IzlaznaFaktura result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NarudzbenicaKupca_IzlaznaFaktura.toString());
		if (identifier != null) {
			result = prodaja.proxies.IzlaznaFaktura.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of NarudzbenicaKupca_IzlaznaFaktura
	 * @param narudzbenicakupca_izlaznafaktura
	 */
	public final void setNarudzbenicaKupca_IzlaznaFaktura(prodaja.proxies.IzlaznaFaktura narudzbenicakupca_izlaznafaktura)
	{
		setNarudzbenicaKupca_IzlaznaFaktura(getContext(), narudzbenicakupca_izlaznafaktura);
	}

	/**
	 * Set value of NarudzbenicaKupca_IzlaznaFaktura
	 * @param context
	 * @param narudzbenicakupca_izlaznafaktura
	 */
	public final void setNarudzbenicaKupca_IzlaznaFaktura(com.mendix.systemwideinterfaces.core.IContext context, prodaja.proxies.IzlaznaFaktura narudzbenicakupca_izlaznafaktura)
	{
		if (narudzbenicakupca_izlaznafaktura == null) {
			getMendixObject().setValue(context, MemberNames.NarudzbenicaKupca_IzlaznaFaktura.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.NarudzbenicaKupca_IzlaznaFaktura.toString(), narudzbenicakupca_izlaznafaktura.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of NarudzbenicaKupca_PoslovniPartner
	 */
	public final myfirstmodule.proxies.PoslovniPartner getNarudzbenicaKupca_PoslovniPartner() throws com.mendix.core.CoreException
	{
		return getNarudzbenicaKupca_PoslovniPartner(getContext());
	}

	/**
	 * @param context
	 * @return value of NarudzbenicaKupca_PoslovniPartner
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.PoslovniPartner getNarudzbenicaKupca_PoslovniPartner(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.PoslovniPartner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NarudzbenicaKupca_PoslovniPartner.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.PoslovniPartner.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of NarudzbenicaKupca_PoslovniPartner
	 * @param narudzbenicakupca_poslovnipartner
	 */
	public final void setNarudzbenicaKupca_PoslovniPartner(myfirstmodule.proxies.PoslovniPartner narudzbenicakupca_poslovnipartner)
	{
		setNarudzbenicaKupca_PoslovniPartner(getContext(), narudzbenicakupca_poslovnipartner);
	}

	/**
	 * Set value of NarudzbenicaKupca_PoslovniPartner
	 * @param context
	 * @param narudzbenicakupca_poslovnipartner
	 */
	public final void setNarudzbenicaKupca_PoslovniPartner(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.PoslovniPartner narudzbenicakupca_poslovnipartner)
	{
		if (narudzbenicakupca_poslovnipartner == null) {
			getMendixObject().setValue(context, MemberNames.NarudzbenicaKupca_PoslovniPartner.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.NarudzbenicaKupca_PoslovniPartner.toString(), narudzbenicakupca_poslovnipartner.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of NarudzbenicaKupca_PoslovnaGodina
	 */
	public final myfirstmodule.proxies.PoslovnaGodina getNarudzbenicaKupca_PoslovnaGodina() throws com.mendix.core.CoreException
	{
		return getNarudzbenicaKupca_PoslovnaGodina(getContext());
	}

	/**
	 * @param context
	 * @return value of NarudzbenicaKupca_PoslovnaGodina
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.PoslovnaGodina getNarudzbenicaKupca_PoslovnaGodina(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.PoslovnaGodina result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NarudzbenicaKupca_PoslovnaGodina.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.PoslovnaGodina.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of NarudzbenicaKupca_PoslovnaGodina
	 * @param narudzbenicakupca_poslovnagodina
	 */
	public final void setNarudzbenicaKupca_PoslovnaGodina(myfirstmodule.proxies.PoslovnaGodina narudzbenicakupca_poslovnagodina)
	{
		setNarudzbenicaKupca_PoslovnaGodina(getContext(), narudzbenicakupca_poslovnagodina);
	}

	/**
	 * Set value of NarudzbenicaKupca_PoslovnaGodina
	 * @param context
	 * @param narudzbenicakupca_poslovnagodina
	 */
	public final void setNarudzbenicaKupca_PoslovnaGodina(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.PoslovnaGodina narudzbenicakupca_poslovnagodina)
	{
		if (narudzbenicakupca_poslovnagodina == null) {
			getMendixObject().setValue(context, MemberNames.NarudzbenicaKupca_PoslovnaGodina.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.NarudzbenicaKupca_PoslovnaGodina.toString(), narudzbenicakupca_poslovnagodina.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of NarudzbenicaKupca_Preduzece
	 */
	public final myfirstmodule.proxies.Preduzece getNarudzbenicaKupca_Preduzece() throws com.mendix.core.CoreException
	{
		return getNarudzbenicaKupca_Preduzece(getContext());
	}

	/**
	 * @param context
	 * @return value of NarudzbenicaKupca_Preduzece
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Preduzece getNarudzbenicaKupca_Preduzece(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Preduzece result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NarudzbenicaKupca_Preduzece.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Preduzece.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of NarudzbenicaKupca_Preduzece
	 * @param narudzbenicakupca_preduzece
	 */
	public final void setNarudzbenicaKupca_Preduzece(myfirstmodule.proxies.Preduzece narudzbenicakupca_preduzece)
	{
		setNarudzbenicaKupca_Preduzece(getContext(), narudzbenicakupca_preduzece);
	}

	/**
	 * Set value of NarudzbenicaKupca_Preduzece
	 * @param context
	 * @param narudzbenicakupca_preduzece
	 */
	public final void setNarudzbenicaKupca_Preduzece(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Preduzece narudzbenicakupca_preduzece)
	{
		if (narudzbenicakupca_preduzece == null) {
			getMendixObject().setValue(context, MemberNames.NarudzbenicaKupca_Preduzece.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.NarudzbenicaKupca_Preduzece.toString(), narudzbenicakupca_preduzece.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return narudzbenicaKupcaMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final prodaja.proxies.NarudzbenicaKupca that = (prodaja.proxies.NarudzbenicaKupca) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
