// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package prodaja.proxies;

public enum StatusFakture
{
	U_Obradi("940906dd-0774-48ef-9b99-5e2fc531b890"),
	Stornirana("99af596a-8cbb-44b9-8f68-5f0746c5d7c8"),
	Obradjena("40be0057-c5b7-48f5-886b-be83af89fc31");

	private final java.lang.String i18nCaptionKey;
	
	private StatusFakture(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
