// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package prodaja.proxies;

public enum StatusUgovora
{
	Aktivan("d0db5430-4aec-4c0c-9872-5909c47eaa6f"),
	Izvrsen("6088dd3a-208f-4e81-bb47-0733e61d9e16"),
	Raskinut("b4918570-7598-4936-9281-5171c8a0ea43"),
	JednostranoOtkazan("5d01eca2-c6bc-4045-8584-b4e0de1026a7"),
	Ponisten("2f4d955b-4cd5-4d8f-8752-aa9c43b7c621");

	private final java.lang.String i18nCaptionKey;
	
	private StatusUgovora(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
