// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package prodaja.proxies;

public enum StatusFakture
{
	UFaziFormiranja("c9d404d2-2e2f-43f3-ba35-bd9e2192d302"),
	Poslata("685829f9-d04d-413c-b224-e487563bb708"),
	Stornirana("1b7a0d35-f9b1-44a6-99b0-a427a05240c1");

	private final java.lang.String i18nCaptionKey;
	
	private StatusFakture(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
