// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package prodaja.proxies;

public class StavkaFakture implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject stavkaFaktureMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Prodaja.StavkaFakture";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		kolicina("kolicina"),
		rabat("rabat"),
		jedinicnaCena("jedinicnaCena"),
		osnovica("osnovica"),
		stopaPDV("stopaPDV"),
		iznosPDV("iznosPDV"),
		ukupno("ukupno"),
		StavkaFakture_IzlaznaFaktura("Prodaja.StavkaFakture_IzlaznaFaktura"),
		StavkaFakture_RobaIliUsluga("Prodaja.StavkaFakture_RobaIliUsluga");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public StavkaFakture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected StavkaFakture(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject stavkaFaktureMendixObject)
	{
		if (stavkaFaktureMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!stavkaFaktureMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.stavkaFaktureMendixObject = stavkaFaktureMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static prodaja.proxies.StavkaFakture initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new prodaja.proxies.StavkaFakture(context, mendixObject);
	}

	public static prodaja.proxies.StavkaFakture load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return prodaja.proxies.StavkaFakture.initialize(context, mendixObject);
	}

	public static java.util.List<prodaja.proxies.StavkaFakture> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> prodaja.proxies.StavkaFakture.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of kolicina
	 */
	public final java.math.BigDecimal getkolicina()
	{
		return getkolicina(getContext());
	}

	/**
	 * @param context
	 * @return value of kolicina
	 */
	public final java.math.BigDecimal getkolicina(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.kolicina.toString());
	}

	/**
	 * Set value of kolicina
	 * @param kolicina
	 */
	public final void setkolicina(java.math.BigDecimal kolicina)
	{
		setkolicina(getContext(), kolicina);
	}

	/**
	 * Set value of kolicina
	 * @param context
	 * @param kolicina
	 */
	public final void setkolicina(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal kolicina)
	{
		getMendixObject().setValue(context, MemberNames.kolicina.toString(), kolicina);
	}

	/**
	 * @return value of rabat
	 */
	public final java.math.BigDecimal getrabat()
	{
		return getrabat(getContext());
	}

	/**
	 * @param context
	 * @return value of rabat
	 */
	public final java.math.BigDecimal getrabat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.rabat.toString());
	}

	/**
	 * Set value of rabat
	 * @param rabat
	 */
	public final void setrabat(java.math.BigDecimal rabat)
	{
		setrabat(getContext(), rabat);
	}

	/**
	 * Set value of rabat
	 * @param context
	 * @param rabat
	 */
	public final void setrabat(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal rabat)
	{
		getMendixObject().setValue(context, MemberNames.rabat.toString(), rabat);
	}

	/**
	 * @return value of jedinicnaCena
	 */
	public final java.math.BigDecimal getjedinicnaCena()
	{
		return getjedinicnaCena(getContext());
	}

	/**
	 * @param context
	 * @return value of jedinicnaCena
	 */
	public final java.math.BigDecimal getjedinicnaCena(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.jedinicnaCena.toString());
	}

	/**
	 * Set value of jedinicnaCena
	 * @param jedinicnacena
	 */
	public final void setjedinicnaCena(java.math.BigDecimal jedinicnacena)
	{
		setjedinicnaCena(getContext(), jedinicnacena);
	}

	/**
	 * Set value of jedinicnaCena
	 * @param context
	 * @param jedinicnacena
	 */
	public final void setjedinicnaCena(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal jedinicnacena)
	{
		getMendixObject().setValue(context, MemberNames.jedinicnaCena.toString(), jedinicnacena);
	}

	/**
	 * @return value of osnovica
	 */
	public final java.math.BigDecimal getosnovica()
	{
		return getosnovica(getContext());
	}

	/**
	 * @param context
	 * @return value of osnovica
	 */
	public final java.math.BigDecimal getosnovica(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.osnovica.toString());
	}

	/**
	 * Set value of osnovica
	 * @param osnovica
	 */
	public final void setosnovica(java.math.BigDecimal osnovica)
	{
		setosnovica(getContext(), osnovica);
	}

	/**
	 * Set value of osnovica
	 * @param context
	 * @param osnovica
	 */
	public final void setosnovica(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal osnovica)
	{
		getMendixObject().setValue(context, MemberNames.osnovica.toString(), osnovica);
	}

	/**
	 * @return value of stopaPDV
	 */
	public final java.math.BigDecimal getstopaPDV()
	{
		return getstopaPDV(getContext());
	}

	/**
	 * @param context
	 * @return value of stopaPDV
	 */
	public final java.math.BigDecimal getstopaPDV(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.stopaPDV.toString());
	}

	/**
	 * Set value of stopaPDV
	 * @param stopapdv
	 */
	public final void setstopaPDV(java.math.BigDecimal stopapdv)
	{
		setstopaPDV(getContext(), stopapdv);
	}

	/**
	 * Set value of stopaPDV
	 * @param context
	 * @param stopapdv
	 */
	public final void setstopaPDV(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal stopapdv)
	{
		getMendixObject().setValue(context, MemberNames.stopaPDV.toString(), stopapdv);
	}

	/**
	 * @return value of iznosPDV
	 */
	public final java.math.BigDecimal getiznosPDV()
	{
		return getiznosPDV(getContext());
	}

	/**
	 * @param context
	 * @return value of iznosPDV
	 */
	public final java.math.BigDecimal getiznosPDV(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.iznosPDV.toString());
	}

	/**
	 * Set value of iznosPDV
	 * @param iznospdv
	 */
	public final void setiznosPDV(java.math.BigDecimal iznospdv)
	{
		setiznosPDV(getContext(), iznospdv);
	}

	/**
	 * Set value of iznosPDV
	 * @param context
	 * @param iznospdv
	 */
	public final void setiznosPDV(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal iznospdv)
	{
		getMendixObject().setValue(context, MemberNames.iznosPDV.toString(), iznospdv);
	}

	/**
	 * @return value of ukupno
	 */
	public final java.math.BigDecimal getukupno()
	{
		return getukupno(getContext());
	}

	/**
	 * @param context
	 * @return value of ukupno
	 */
	public final java.math.BigDecimal getukupno(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ukupno.toString());
	}

	/**
	 * Set value of ukupno
	 * @param ukupno
	 */
	public final void setukupno(java.math.BigDecimal ukupno)
	{
		setukupno(getContext(), ukupno);
	}

	/**
	 * Set value of ukupno
	 * @param context
	 * @param ukupno
	 */
	public final void setukupno(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ukupno)
	{
		getMendixObject().setValue(context, MemberNames.ukupno.toString(), ukupno);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of StavkaFakture_IzlaznaFaktura
	 */
	public final prodaja.proxies.IzlaznaFaktura getStavkaFakture_IzlaznaFaktura() throws com.mendix.core.CoreException
	{
		return getStavkaFakture_IzlaznaFaktura(getContext());
	}

	/**
	 * @param context
	 * @return value of StavkaFakture_IzlaznaFaktura
	 * @throws com.mendix.core.CoreException
	 */
	public final prodaja.proxies.IzlaznaFaktura getStavkaFakture_IzlaznaFaktura(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		prodaja.proxies.IzlaznaFaktura result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StavkaFakture_IzlaznaFaktura.toString());
		if (identifier != null) {
			result = prodaja.proxies.IzlaznaFaktura.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of StavkaFakture_IzlaznaFaktura
	 * @param stavkafakture_izlaznafaktura
	 */
	public final void setStavkaFakture_IzlaznaFaktura(prodaja.proxies.IzlaznaFaktura stavkafakture_izlaznafaktura)
	{
		setStavkaFakture_IzlaznaFaktura(getContext(), stavkafakture_izlaznafaktura);
	}

	/**
	 * Set value of StavkaFakture_IzlaznaFaktura
	 * @param context
	 * @param stavkafakture_izlaznafaktura
	 */
	public final void setStavkaFakture_IzlaznaFaktura(com.mendix.systemwideinterfaces.core.IContext context, prodaja.proxies.IzlaznaFaktura stavkafakture_izlaznafaktura)
	{
		if (stavkafakture_izlaznafaktura == null) {
			getMendixObject().setValue(context, MemberNames.StavkaFakture_IzlaznaFaktura.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.StavkaFakture_IzlaznaFaktura.toString(), stavkafakture_izlaznafaktura.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of StavkaFakture_RobaIliUsluga
	 */
	public final myfirstmodule.proxies.RobaIliUsluga getStavkaFakture_RobaIliUsluga() throws com.mendix.core.CoreException
	{
		return getStavkaFakture_RobaIliUsluga(getContext());
	}

	/**
	 * @param context
	 * @return value of StavkaFakture_RobaIliUsluga
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.RobaIliUsluga getStavkaFakture_RobaIliUsluga(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.RobaIliUsluga result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StavkaFakture_RobaIliUsluga.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.RobaIliUsluga.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of StavkaFakture_RobaIliUsluga
	 * @param stavkafakture_robailiusluga
	 */
	public final void setStavkaFakture_RobaIliUsluga(myfirstmodule.proxies.RobaIliUsluga stavkafakture_robailiusluga)
	{
		setStavkaFakture_RobaIliUsluga(getContext(), stavkafakture_robailiusluga);
	}

	/**
	 * Set value of StavkaFakture_RobaIliUsluga
	 * @param context
	 * @param stavkafakture_robailiusluga
	 */
	public final void setStavkaFakture_RobaIliUsluga(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.RobaIliUsluga stavkafakture_robailiusluga)
	{
		if (stavkafakture_robailiusluga == null) {
			getMendixObject().setValue(context, MemberNames.StavkaFakture_RobaIliUsluga.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.StavkaFakture_RobaIliUsluga.toString(), stavkafakture_robailiusluga.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return stavkaFaktureMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final prodaja.proxies.StavkaFakture that = (prodaja.proxies.StavkaFakture) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
