// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package prodaja.proxies;

public class StavkaNarudzbenice implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject stavkaNarudzbeniceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Prodaja.StavkaNarudzbenice";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		kolicina("kolicina"),
		StavkaNarudzbenice_NarudzbenicaKupca("Prodaja.StavkaNarudzbenice_NarudzbenicaKupca"),
		StavkaNarudzbenice_RobaIliUsluga("Prodaja.StavkaNarudzbenice_RobaIliUsluga");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public StavkaNarudzbenice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected StavkaNarudzbenice(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject stavkaNarudzbeniceMendixObject)
	{
		if (stavkaNarudzbeniceMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!stavkaNarudzbeniceMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.stavkaNarudzbeniceMendixObject = stavkaNarudzbeniceMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static prodaja.proxies.StavkaNarudzbenice initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new prodaja.proxies.StavkaNarudzbenice(context, mendixObject);
	}

	public static prodaja.proxies.StavkaNarudzbenice load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return prodaja.proxies.StavkaNarudzbenice.initialize(context, mendixObject);
	}

	public static java.util.List<prodaja.proxies.StavkaNarudzbenice> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> prodaja.proxies.StavkaNarudzbenice.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of kolicina
	 */
	public final java.math.BigDecimal getkolicina()
	{
		return getkolicina(getContext());
	}

	/**
	 * @param context
	 * @return value of kolicina
	 */
	public final java.math.BigDecimal getkolicina(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.kolicina.toString());
	}

	/**
	 * Set value of kolicina
	 * @param kolicina
	 */
	public final void setkolicina(java.math.BigDecimal kolicina)
	{
		setkolicina(getContext(), kolicina);
	}

	/**
	 * Set value of kolicina
	 * @param context
	 * @param kolicina
	 */
	public final void setkolicina(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal kolicina)
	{
		getMendixObject().setValue(context, MemberNames.kolicina.toString(), kolicina);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of StavkaNarudzbenice_NarudzbenicaKupca
	 */
	public final prodaja.proxies.NarudzbenicaKupca getStavkaNarudzbenice_NarudzbenicaKupca() throws com.mendix.core.CoreException
	{
		return getStavkaNarudzbenice_NarudzbenicaKupca(getContext());
	}

	/**
	 * @param context
	 * @return value of StavkaNarudzbenice_NarudzbenicaKupca
	 * @throws com.mendix.core.CoreException
	 */
	public final prodaja.proxies.NarudzbenicaKupca getStavkaNarudzbenice_NarudzbenicaKupca(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		prodaja.proxies.NarudzbenicaKupca result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StavkaNarudzbenice_NarudzbenicaKupca.toString());
		if (identifier != null) {
			result = prodaja.proxies.NarudzbenicaKupca.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of StavkaNarudzbenice_NarudzbenicaKupca
	 * @param stavkanarudzbenice_narudzbenicakupca
	 */
	public final void setStavkaNarudzbenice_NarudzbenicaKupca(prodaja.proxies.NarudzbenicaKupca stavkanarudzbenice_narudzbenicakupca)
	{
		setStavkaNarudzbenice_NarudzbenicaKupca(getContext(), stavkanarudzbenice_narudzbenicakupca);
	}

	/**
	 * Set value of StavkaNarudzbenice_NarudzbenicaKupca
	 * @param context
	 * @param stavkanarudzbenice_narudzbenicakupca
	 */
	public final void setStavkaNarudzbenice_NarudzbenicaKupca(com.mendix.systemwideinterfaces.core.IContext context, prodaja.proxies.NarudzbenicaKupca stavkanarudzbenice_narudzbenicakupca)
	{
		if (stavkanarudzbenice_narudzbenicakupca == null) {
			getMendixObject().setValue(context, MemberNames.StavkaNarudzbenice_NarudzbenicaKupca.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.StavkaNarudzbenice_NarudzbenicaKupca.toString(), stavkanarudzbenice_narudzbenicakupca.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of StavkaNarudzbenice_RobaIliUsluga
	 */
	public final myfirstmodule.proxies.RobaIliUsluga getStavkaNarudzbenice_RobaIliUsluga() throws com.mendix.core.CoreException
	{
		return getStavkaNarudzbenice_RobaIliUsluga(getContext());
	}

	/**
	 * @param context
	 * @return value of StavkaNarudzbenice_RobaIliUsluga
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.RobaIliUsluga getStavkaNarudzbenice_RobaIliUsluga(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.RobaIliUsluga result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StavkaNarudzbenice_RobaIliUsluga.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.RobaIliUsluga.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of StavkaNarudzbenice_RobaIliUsluga
	 * @param stavkanarudzbenice_robailiusluga
	 */
	public final void setStavkaNarudzbenice_RobaIliUsluga(myfirstmodule.proxies.RobaIliUsluga stavkanarudzbenice_robailiusluga)
	{
		setStavkaNarudzbenice_RobaIliUsluga(getContext(), stavkanarudzbenice_robailiusluga);
	}

	/**
	 * Set value of StavkaNarudzbenice_RobaIliUsluga
	 * @param context
	 * @param stavkanarudzbenice_robailiusluga
	 */
	public final void setStavkaNarudzbenice_RobaIliUsluga(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.RobaIliUsluga stavkanarudzbenice_robailiusluga)
	{
		if (stavkanarudzbenice_robailiusluga == null) {
			getMendixObject().setValue(context, MemberNames.StavkaNarudzbenice_RobaIliUsluga.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.StavkaNarudzbenice_RobaIliUsluga.toString(), stavkanarudzbenice_robailiusluga.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return stavkaNarudzbeniceMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final prodaja.proxies.StavkaNarudzbenice that = (prodaja.proxies.StavkaNarudzbenice) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
