// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package prodaja.proxies;

public enum StopaPDV
{
	Oslobodjen("0fad759f-254b-4b4a-a8e7-ae32d88008bc"),
	Srednja("22fbece2-f793-4627-895c-0c5141f2a48c"),
	Visa("04a9f346-a33b-415c-8b35-0dd732ce319c");

	private final java.lang.String i18nCaptionKey;
	
	private StopaPDV(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
