// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package prodaja.proxies;

public enum StopaPDV
{
	Oslobodjen("77f927da-8865-419a-84d8-eabc0e4677ff"),
	Srednji("12cc9d11-1ff8-44c5-a28b-dcead8143bed"),
	Visoki("1b3c63e3-a65d-44f9-bf30-1335efd0c0dd");

	private final java.lang.String i18nCaptionKey;
	
	private StopaPDV(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
