// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package prodaja.proxies;

public enum VrstaDokumenta
{
	Profaktura("11a83311-e438-4025-bc91-2630643f4c91"),
	Faktura("044ed386-3f14-4755-ab88-5668ccd8ab0c");

	private final java.lang.String i18nCaptionKey;
	
	private VrstaDokumenta(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
